### ISSUE TITLE
Captcha: Save "humanity" in Session

### ISSUE THREAD

**Issue by claudehohl** [claudehohl/Stikked#107]
...so that I only have to type it once.

**Comment by krangownik** [comment]
if you are giving too much rights for humans they are doing to much mess
how I can simply turn of that humanity option?
Krang want that everybody everytime need to put captcha code!
thanks

**Comment by claudehohl** [comment]
Hmm yea, I'd have to implement it. And the config grows bigger and bigger... :/

**Comment by krangownik** [comment]
Yeah I understand. It's not so important. You are doing great work! Don't stop!

**Comment by claudehohl** [comment]
<3 thank you!
I'll implement it, I just need to allocate some time for Stikked...
