### ISSUE TITLE
Not possible to force https anyway

### ISSUE THREAD

**Issue by Shadowghost** [claudehohl/Stikked#121]
I tried to force stikked to use https with .htacces and mod_rewrite or even with v-host but everytime the complete URL got mixed up.

Edit: Even if you typed https:// directly before the URL you get an 404 error because of wrong rewritte URL. it rewrited it with ./DIRECTORY_NAME_AT_YOUR_WEBSERVER/?/ instead of ./

**Comment by Banochkin** [comment]
base_url is not redirect to https url. How can i do it? .htacces is don't work.
