### ISSUE TITLE
stikked + sqlite3. how?

### ISSUE THREAD

**Issue by sl1pkn07** [claudehohl/Stikked#124]
hi

i want install stikked with sqlite database

i've configured php.ini with enable sqlite3.so extensions

and edit the file https://github.com/claudehohl/Stikked/blob/master/htdocs/application/config/database.php#L57

and change to 'sqlite'

none of other file is change

but the load stikked give blank page
(error 500 in lighttpd log and firefox(firebug)/chromium(object inspector)

need other step?

greetings

**Comment by claudehohl** [comment]
https://github.com/claudehohl/Stikked/commit/ab3afec3f466409a130fdd81b61edaccaf7a79cd
