### ISSUE TITLE
/view/[id] not found

### ISSUE THREAD

**Issue by julius-s** [claudehohl/Stikked#129]
Hi all,
claudehohl, thanks for your work on Stikked.
I know this was previously discussed in #37 but I'm having the same issue with regards to /view/\* page not found. I can visit the home page http://pastebin.com (workstation hosts entry for pastebin.com points to dev server)

I am running Debian lenny + php5.2 and I have followed the recommended solution and still getting the issue. I have in my vhost file:

< VirtualHost *:80 >

<pre>
  ServerName pastebin.com
  ServerAlias dev.pastebin.com

  DocumentRoot /home/username/dev/pastebin/web
  
  CustomLog /var/log/pastebin-access.log combined
  ErrorLog /var/log/pastebin/error.log
</pre>

   < Directory "/home/username/dev/pastebin/web" >

<pre>        
Options +FollowSymLinks
        AllowOverride all
        Order allow,deny
        Allow from all
</pre>

  < / Directory >

< / VirtualHost >

The content of the /home/username/dev/pastebin/web is basically copied from Stikked/htdocs directory.

mod_rewrite is enabled:

$ a2enmod rewrite
Module rewrite already enabled

In my config.php I have only changed:
$config['base_url'] = 'http://pastebin.com/';

and in my stikked.php I have only changed my database params.

Please  is there anything you can think of that I'm done/doing wrong?

I debugged for hours and still can't get the view/\* to work

Thanks a lot

**Comment by JialuZhang** [comment]
@julius-s

The default value of “RewriteEngine" is already an "off", so instead of the “RewriteEngine" is overwritten to "off", it is by default turned off by Apache. Thanks!

Related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```
