### ISSUE TITLE
[Enhancement]  ACE editor

### ISSUE THREAD

**Issue by gaz492** [claudehohl/Stikked#134]
Have the option to use ACE instead of code mirror.
Personally it feels nicer to use than codemirror

**Comment by claudehohl** [comment]
Damn. Again haven't made it...

**Comment by tyrollins** [comment]
Any plans to include this in the next release?

**Comment by claudehohl** [comment]
https://ace.c9.io/#nav=embedding

**Comment by claudehohl** [comment]
* ace is fucking huge. >500kb javascript!
* option to select: codemirror or ace.
* auto-enable editor (remove "enable realtime syntax highlighting")
* textarea is fallback for non-js

**Comment by tyrollins** [comment]
True, Ace is ridiculously big, but it's worth it in my opinion haha. If someone were to write actually write code in the editor and not just copy and paste it in, I'd go with Ace. Totally agree with auto-enabling the editor and having the text area as a fallback. Not sure you need the option to choose codemirror or ace, seems like it should be one or the other client side (unless you mean option for devs).

Awesome work though! I appreciate it!

**Comment by claudehohl** [comment]
already built it, about to getting it done :)
i want server-admins to choose whether to serve a 800kb js file or keep it small.

**Comment by claudehohl** [comment]
https://github.com/claudehohl/Stikked/commits/ace-editor

**Comment by claudehohl** [comment]
fixed. \o/
