### ISSUE TITLE
Blank page, 500 Internal Server Error, nothing in error log

### ISSUE THREAD

**Issue by ccaughie** [claudehohl/Stikked#139]
I've just tried to install stikked (twice) following the instructions to the letter. I'm using Debian Linux (wheezy) and Apache, fully updated, and am using the supplied Apache site script with only name changes for my site. I've installed PHP5.

When I try to connect I get a completely blank page every time, with or without using "index.php" in the URL. A Wireshark capture reveals that the server is in fact sending a "500 Internal Server Error" response, with a Content-Type of text/html but the content is actually 20 bytes of binary data.

The 20 bytes, in case it helps, are:

1f 8b 08 00 00 00 00 00 00 03 03 00 00 00 00 00 00 00 00 00

The error log is completely empty. I can't find anything in the documentation about how to enable more logging.

**Comment by tcpepidemic** [comment]
Old issue, but i just ran into a similar problem so maybe this can help someone.
In my case i had forgotten to install php-mysql (I'm using nginx,php,mysql and php-fpm on openbsd) mysql is not part of the default php package (in OpenBSD packages). No errors in any logfiles, only 500 codes returned.
Maybe there should be a page with requirements to help stupid people like me :) (i looked for one during my troubleshooting but could not find it, it could have saved me more time than i will admit).

**Comment by claudehohl** [comment]
codeigniter has been updated to 3.x, try it - and reopen issue if the error still happens.
