### ISSUE TITLE
The application environment is not set correctly.

### ISSUE THREAD

**Issue by dustin-lennon** [claudehohl/Stikked#148]
There is something that is causing the ENVIRONMENT not to read properly when set to 'PRODUCTION' or 'TESTING' to where it results in displaying the default option from the switch statement.

When moving it to another environment temporarily and switching it back to what it was originally temporarily resolves the issue.

The only thing I can see when viewing the log file output by CodeIgniter is this:
`ERROR - 2014-06-15 19:05:56 --> Severity: Notice  --> Only variable references should be returned by reference /var/www/Stikked/htdocs/system/core/Common.php 257` and this `ERROR - 2014-06-15 19:05:56 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead /var/www/Stikked/htdocs/system/database/drivers/mysql/mysql_driver.php 91`. I don't know if either one of these issues is contributing to the issue I am having.

Is there anything else that can be done to debug this?

**Comment by nencerjsc** [comment]
good solution. i am a beginner =))
