### ISSUE TITLE
password protect option ?

### ISSUE THREAD

**Issue by TurkDesk** [claudehohl/Stikked#150]
is there a password protecting option that i don't see ? ie: whoever does a paste can put a password they choose, so if anyone else want to see the paste should use password to have permission..

**Comment by mbressman** [comment]
Hi - just wondering if this was ever implemented?  Don't see it on paste.scratchbook.ch and was under the impression paste.scratchbook.ch was a demo of this product (but perhaps it hasn't been updated in a while).  Just figured I'd ask here - thanks!
