### ISSUE TITLE
[Enhancement] drag & drop files support

### ISSUE THREAD

**Issue by truhlikfredy** [claudehohl/Stikked#157]
Would possible to support  drag & drop files support?

Or it takes too much work for very niche feature.

Btw: your fork of stikked is very nicely done, was installing the original and yours and you can see that in yours there is much more effort put into all of this.

**Comment by claudehohl** [comment]
note to myself: http://www.dropzonejs.com/

**Comment by claudehohl** [comment]
better variant without file uploads: http://stackoverflow.com/questions/12214057/drag-n-drop-text-file
