### ISSUE TITLE
Enable Api key and allow viewing api description page

### ISSUE THREAD

**Issue by BalzySte** [claudehohl/Stikked#162]
Hello,
Since my Stikked platform is public, I'd like to set an API key in order to prevent spam but I still want users to be able to view the example page. There I would add a line saying "ask me a the api key @mail address". Could you please explain me how to achieve it (if possibile and simple) or add this feature to the next version?
All I figured out is editing the api link in the theme header page but the key would be visible then.

Thank you
Regards
Stefano

**Comment by claudehohl** [comment]
Oh holy shit yes, the API page is dead. Bummer... fixing.
