### ISSUE TITLE
Stikked does not work with IPv6 Clients

### ISSUE THREAD

**Issue by ThomasLeister** [claudehohl/Stikked#169]
Hi,

a few minutes ago I instelled my first instance of Stikked. I found out that viewing a paste while having IPv6 enabled leads to a database error. 

I don't want to log IP adresses anyway so i replaced every IP-function or variable by "127.0.0.1"... now it's working :)

**Comment by claudehohl** [comment]
ip_address is at 45 chars (https://github.com/claudehohl/Stikked/blob/master/htdocs/application/controllers/main.php#L214), closing...
