### ISSUE TITLE
Several issues on setup

### ISSUE THREAD

**Issue by Doooooo0o** [claudehohl/Stikked#19]
As the INSTALL doc was pretty simple, I followed it, but I experienced some issues :

at first, I didn't get any captcha even if I activated them in application/config/stikked.php, 
I thought it was a typical pebkac, but then I disabled it to paste without captcha, and i get that error :

The requested URL /view/c738d9f8 was not found on this server.

so I created the /view folder, and chown'd it, but it didn't fixed my issue ...

**Comment by Owned67** [comment]
Enable reqrite for apache2 :)
