### ISSUE TITLE
disable_shorturl behaviour

### ISSUE THREAD

**Issue by glensc** [claudehohl/Stikked#205]
```php
$config['disable_shorturl'] = true;
```

the behaviour of this parameter (at least in default skin) is that shorturl checkbox can't be checked. but i really expected the option to remove completely shorturl checkbox to cleanup the ui

if you need both behaviours, i suggest:
- `$config['enable_shorturl'] = true;` - checkbox is present and checkable
- `$config['enable_shorturl'] = false;` - checkbox is present and not checkable
- `$config['enable_shorturl'] = null;` - the checkbox is removed from page

but i don't see why would one want to see checkbox that can't be used, looks like technical limitation or just a quick hack.

**Comment by claudehohl** [comment]
ah, i see its already removed. closing...
