### ISSUE TITLE
[RESOLVE] Trending & Recent API Error 

### ISSUE THREAD

**Issue by filereal** [claudehohl/Stikked#207]
hi it look like there is error in trending api 
i got this error 

Error Number: 1327
Undeclared variable: trending
SELECT id, title, name, created, pid, lang, raw, hits FROM pastes WHERE private = 0 AND (title LIKE '%%' OR raw LIKE '%%') ORDER BY hits DESC, created DESC LIMIT trending,15
Filename: xxxx\database\DB_driver.php
Line Number: 330

**Comment by kalaker** [comment]
Fixed with #246
