### ISSUE TITLE
Backend admin

### ISSUE THREAD

**Issue by krangownik** [claudehohl/Stikked#219]
New version is great!
Idea with encrypted pastes and burn on reading as expiration is awesome!
Great, good job men!
For few weeks I will be making some changes on InserTor (pastebin clone in Tor on your script) and will update to new version. There will be information about that script is created by you and some info how to make donations for your project! Everyone on earth must know about you and stikked!
So keep going.

I have some ideas, maybe it will be interesting for you.
-Captcha protection system - on simply mathematical equation (you know, some mix, 5-_=2 or _x4=12 or 2+2=_)
-Search options - everyone can search everything (every paste)
-Small backend admin - only for easy remove pastes which are bad (now if I need to delete paste I need to delete it from database, it is horrible)

have nice day human

**Comment by claudehohl** [comment]
this duplicates https://github.com/claudehohl/Stikked/issues/38, so i'm closing it. heavy-heartedly since this is such a nice conversation :)
