### ISSUE TITLE
Encrypt Metadata  Author and Title

### ISSUE THREAD

**Issue by nitmir** [claudehohl/Stikked#227]
Hi,
When creating en encrypted paste, only the core of the paste is encryted : Author and Title are not.
(example http://paste.scratchbook.ch/view/b8999dab ).
It would be nice to encrypt this meta-data or at least to warn that there are not.

Edit: idem for the Language field

**Comment by claudehohl** [comment]
Just leave the "metadata" empty so that's randomized.
