### ISSUE TITLE
Bootstrap theme doesn't recognise smartphone

### ISSUE THREAD

**Issue by Kondra007** [claudehohl/Stikked#229]
Hello! I have Galaxy S4 phone with 1080x1920 resolution.
Bootstrap theme thinks I have a PC and shows full version. 

Can you fix it?

**Comment by benjaminarthurt** [comment]
I was able to correct this by adding: <meta name="viewport" content="width=device-width, initial-scale=1"> to /themes/bootstrap/views/defaults/header.php

**Comment by benjaminarthurt** [comment]
meta name="viewport" content="width=device-width, initial-scale=1" as a tag in the head

**Comment by claudehohl** [comment]
Merged, fixed. Thanks!
