### ISSUE TITLE
Random string for unknown titled posts

### ISSUE THREAD

**Issue by barknezz** [claudehohl/Stikked#230]
Hey folks.
This might help preventing duplicated titles.

Open application/config/stikked.php

Find $config['unknown_title'] and delete the whole line.

Paste this:

$salla = substr(str_shuffle("abcdefghijklmnopqrstuvyz"), 0, 1) . substr(str_shuffle("abcdefghijklmnopqrstuvyz"), 0, 7);
$config['unknown_title'] = 'Unknown Title ('.$salla.')';

That's it. Now you'll have titles like "Random Title (zvukqzlj)" or "Random Title (noenudyq)"

**Comment by TehPeGaSuS** [comment]
Sorry for bumping such an old issue, but was this implemented in any way?

**Comment by The-Compiler** [comment]
What's there to implement? From what I can see, this is just a suggestion for something to put into your config?

**Comment by TehPeGaSuS** [comment]
I mean, if we have any `random` option like we have on `$config['unknown_poster'] = 'random';`
