### ISSUE TITLE
Shorturl Error: Input provided by user is not valid

### ISSUE THREAD

**Issue by linuxman** [claudehohl/Stikked#236]
Hello friends, I see that there are many updates and new features in stikked.

But I see that there is a problem when creating a short link, the message appears:

    Shorturl Error: Input provided by user is not valid

Greetings !!!

**Comment by benjaminarthurt** [comment]
This is likely an issue with gw.gd I get the same with my local installation if I have reCaptcha enable when trying to use the API.

**Comment by benjaminarthurt** [comment]
I just submitted a pull request to the https://github.com/chusopr/casimir project (what gw.gd is based on). The commit was done last night. This allows you to leave the reCaptcha enabled and have an API key to bypass it. https://github.com/chusopr/casimir/commit/1d1ad18cf05f6a63af010a9b724baf1e7ca04cac 

gw.gd is technically a fork of casimir so the author there will need to bring in these most recent changes although technically casimir works the same way. We Will need to make a few changes here once that happens so stikked can supply the correct API key on API calls to the link shortener. I'm already working on this.

**Comment by claudehohl** [comment]
Thank you @benjaminarthurt for the fix!
