### ISSUE TITLE
API Enhancements

### ISSUE THREAD

**Issue by kalaker** [claudehohl/Stikked#243]
It's likely that as Stikked grows and changes, the API may as well (especially if logins become are supported ;) ). It would be useful if there was a way to access the installed version of Stikked through the API. 

Would it be possible to implement the protected/encrypted pastes feature over the API? Maybe it could be implemented like the private setting, by doing `encrypted=1` in the HTTP request.

**Comment by AdrianKoshka** [comment]
I guess this could be considered an asshat thing to do(necrobumping) but is this project even alive anymore? I was recently also curious about this so is **anyone** can point me to a fork w/ such functionality(specifying `encryped=1` or something like it through API) It would be appreciated

**Comment by The-Compiler** [comment]
@AdrianKoshka the project certainly is alive, it's just that @claudehohl is currently busy with other stuff. The milestone date for v0.9.1 is set for end of September, so expect things tagged for then to be finished by then.

Of course, contributions would be welcome - so if you know PHP, I suggest someone of you implements this and sends a pull request :wink:

**Comment by AdrianKoshka** [comment]
I don't know the first thing about PHP at the moment, before I started poking around the merge requests I hadn't seen that @The-Compiler .

**Comment by xZero707** [comment]
I really like this project, and I wan't to contribute, but I'm busy too. However planning to bring some great enhancements in near future. 
This project have great potential to grow into something big, but there is need for more contributors (developers).

**Comment by AdrianKoshka** [comment]
Yeah at this point in time I'd need to learn PHP and/or JS(and probably JSON also) to be of any help.

**Comment by claudehohl** [comment]
I will be working on Stikked this week, yiiha!
