### ISSUE TITLE
database error 

### ISSUE THREAD

**Issue by abbaselmas** [claudehohl/Stikked#249]
when I manually add /rss to trends page below error occurrs

A Database Error Occurred

Error Number: 1327

Undeclared variable: rss

SELECT id, title, name, created, pid, lang, raw, hits FROM pastes WHERE private = 0 AND (title LIKE '%%' OR raw LIKE '%%') ORDER BY hits DESC, created DESC LIMIT rss,15

Filename: /home/aelmas/sub/paste/models/pastes.php

Line Number: 560

**Comment by kalaker** [comment]
This is probably related #240, #188, and #207, and can most likely be fixed in a way similar to how #246 fixed those three bugs.
