### ISSUE TITLE
Crontab entry

### ISSUE THREAD

**Issue by vniksic** [claudehohl/Stikked#254]
In the docs you can find an example for the crontab entry for cleanup:

"* */5 * * * * curl --silent http://yoursite.com/cron/[key]"

This is incorrect and should be something like:
"* */5 * * * curl --silent http://yoursite.com/cron/[key]"

One of the * is superfluous.

**Comment by claudehohl** [comment]
Oh bummer, you are reading the plain text version of the README.MD

The "suberflous" * is actually the bullet point that is renderet correctly on GitHub: https://github.com/claudehohl/Stikked#installation #run every 5mins

**Comment by vniksic** [comment]
Oh, my bad. That makes sense! :)

**Comment by HyperHCl** [comment]
Maybe @claudehohl can try using the Markdown &lt;code&gt; stuff: `*/5 * * * * curl --silent http://yoursite.com/cron/[key]`

```Markdown
* To ensure that pastes with an expiration set get cleaned up, define the cron key in the config and set up a cronjob, for example:
  * `*/5 * * * * curl --silent http://yoursite.com/cron/[key]`
```

**Comment by claudehohl** [comment]
Good idea, done :)
