### ISSUE TITLE
Possible spam with encrypted function

### ISSUE THREAD

**Issue by Zatalyz** [claudehohl/Stikked#255]
When I create a paste and click on "Create encrypted", captcha is ignored : I can post without validate captcha. Possible way for spam ? 

I don't see option to desactivate encrypted paste in stikked.php

**Comment by claudehohl** [comment]
What use is a spam that nobody can read? ;)

**Comment by Zatalyz** [comment]
Ok, so no problem :)
I test this version alone, and don't understand all ^^"

Thanks for your fast answer !

**Comment by Mikaela** [comment]
Could it have something to do with causing resource usage with server?

**Comment by PJanisio** [comment]
Yes it does, i was forced to remove API because of: "517007 spam-pastes repelled. View blocked IPs." So when it is possible, we should implement captcha.

**Comment by kalaker** [comment]
There will never be a captcha when using the API, so I don't see how you deactivating that is related to there not being a captcha on encrypted pastes. Can you please explain?

**Comment by PJanisio** [comment]
@kalaker 
I was only confirming what Mikaela said that spam attempts (succesfully or not) are causing resource usage.

Anyway API is one thing and encrypted pastes are second, both are vulnerable to spam attempts.

**Comment by kalaker** [comment]
Yeah, the resource usage is there for encrypted pastes, so maybe a captcha would be helpful. 

Also, have you considered an API key rather than flat-out disabling?
