### ISSUE TITLE
Stikked makes pastes, but doesn't create folders

### ISSUE THREAD

**Issue by shawneric** [claudehohl/Stikked#256]
I'm using a standard LDAP server with linode. I'm using apache on ubuntu 14.10 and have applied the following .htacess file information and enabled the modrewrite for apache.

Everytime I create a test paste, it creates it in the database, but does not create a file or folder on the server. Here is a copy of my .htaccess which is located in this folder structure: /var/www/html/paste/

RewriteEngine on
#RewriteBase /
RewriteCond $1 !^(index\.php|static|favicon\.ico|robots\.txt)
RewriteRule ^(.*)$ index.php?/$1 [QSA,L]

SetOutputFilter DEFLATE
FileETag MTime Size

<VirtualHost *:80>
    ServerName Slavery Report
    DocumentRoot /var/www/html/paste/
    ErrorLog ${APACHE_LOG_DIR}/stikked-error_log
    CustomLog ${APACHE_LOG_DIR}/stikked-access_log common
    <Directory "/var/www/html/paste/">
        Options +FollowSymLinks
        AllowOverride All
        Order allow,deny
        Allow from all
    </Directory>
</VirtualHost>

<IfModule !mod_rewrite>
    ErrorDocument 404 /index.php
</IfModule>

<IfModule mod_expires>
    ExpiresActive On
    ExpiresByType text/javascript "access plus 1 year"
    ExpiresByType application/x-javascript "access plus 1 year"
    ExpiresByType application/javascript "access plus 1 year"
    ExpiresByType text/css "access plus 1 year"
    ExpiresByType image/jpeg "access plus 1 year"
    ExpiresByType image/jpg "access plus 1 year"
    ExpiresByType image/gif "access plus 1 year"
    ExpiresByType image/png "access plus 1 year"
    ExpiresByType image/x-icon "access plus 1 year"
		ExpiresByType application/font-woff "access plus 1 year"
    ExpiresByType application/vnd.ms-fontobject "access plus 1 year"
    ExpiresByType application/x-font-ttf "access plus 1 year"
    ExpiresByType font/opentype "access plus 1 year"
    ExpiresByType image/svg+xml "access plus 1 year"
</IfModule>

#AuthType Basic
#AuthName "Backend"
#AuthUserFile /path/to/.htpasswd #create one with htpasswd -c .htpasswd username
#Require user username

**Comment by kalaker** [comment]
No files will ever be created, it's all in the database.
