### ISSUE TITLE
Stikked no captcha

### ISSUE THREAD

**Issue by epicblood** [claudehohl/Stikked#257]
Hello,
I just installed Stikked, and the captcha images show as the broken image icon.
Am I doing something wrong or missing a library?

I am running debian 7 and using nginx to host.

**Comment by Mikaela** [comment]
Did you configure the captcha?

* https://github.com/claudehohl/Stikked/blob/0.9.0/htdocs/application/config/stikked.php.dist#L121-138

**Comment by epicblood** [comment]
not sure how i missed that, sorry about that.
