### ISSUE TITLE
Captcha display doesn't work

### ISSUE THREAD

**Issue by Cramix** [claudehohl/Stikked#258]
Hello,

The captcha isn't display and phpgd is installed. Here is my ngnix configuration:
server {
        listen   80;
        root /var/www/stikked/htdocs;
        index index.php index.html index.htm;
        server_name aaaa.aa;
        location / {
                try_files $uri $uri/ /index.html /;
        }
        error_page 404 /404.html;
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
              root /usr/share/nginx/www;
        }
        location ~ \.php$ {
                try_files $uri =404;
                fastcgi_pass unix:/var/run/php5-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;                
        }
}

Any ideas of what is wrong?
Thank you

**Comment by claudehohl** [comment]
No idea. What's in ur php.ini?

Closing issue due to long inactivity, please reopen if it still happens.
