### ISSUE TITLE
Copyright issue with Geocities template

### ISSUE THREAD

**Issue by Krzysiu** [claudehohl/Stikked#260]
As far as I find this joke great, I think it should be trimmed a bit. There are copyrighted images and in theory somebody could get sued (like copyrighted logos). Of course it's just pure theory, but in same way one won't put copyrighted image in code if there's virtually no chance to get spotted and sued by owner. And now in fact you released e.g. IE logo on CC-0. 

I propose deleting all copyrighted images and exchanging it for open things. It will look worse then, but instead you could put animated visit counter. It was very popular back then. Or static with 123456789. These fake counters were very popular. I'm busy in next days, but if you wish I could make soon a static one and release it on CC-0 :)

**Comment by claudehohl** [comment]
Fuck copyright, real artists steal!
