### ISSUE TITLE
Project has wrong license

### ISSUE THREAD

**Issue by Krzysiu** [claudehohl/Stikked#261]
I was writting about copyright issues with Geocities theme images vs. CC-0 and now I noticed that your project is derivative work of original project, therefore it can't be licensed on CC-0. The original project was on CC-BY-SA 3.0, so even if there's no original code left, you can't put it on CC-0. And even if you want to contribute your changes as CC-0, you can't, because it's SA variant, which makes that you have to release your changes and additions on same license.

**Comment by claudehohl** [comment]
I can because I can. You claim that I can't, but I already did. It's pretty simple: You just commit a license text file into the repository - done.

Seriously, I don't care about that license crap. I probably should have it released under the WTFPL. http://www.wtfpl.net/
