### ISSUE TITLE
Clickable links

### ISSUE THREAD

**Issue by LazyLama** [claudehohl/Stikked#262]
is there a way to have http/s clickable when reading a paste

**Comment by LazyLama** [comment]
It's not really an issue, but pastebin does it and i cant figure out how to tweak the code to do it. Any help would be much appreciated.

**Comment by claudehohl** [comment]
Code gets processed by geshi, which already does some html handling. So I don't know how much effort is required to having clicks linkable without screwing up the html code... Closing for now.

**Comment by xZero707** [comment]
Could be done through javascript.

**Comment by claudehohl** [comment]
Yes but I want a highlighted syntax without javascript...

**Comment by xZero707** [comment]
I mean it is possible to implement standalone, only for converting raw urls to <a href='...'>...</a>
It can be avail only for users with JS enabled, that's it, only that feature would be JS dependent, same as Googlevil ( :+1:  ) captcha.

**Comment by claudehohl** [comment]
ah never mind, i confused two issues. so you mean converting the urls in a paste via javascript to clickable links? yes why not, go ahead ;)
