### ISSUE TITLE
Unable to load the requested language file

### ISSUE THREAD

**Issue by TME97** [claudehohl/Stikked#264]
An Error Was Encountered

Unable to load the requested language file: language/german/db_lang.php

I got this error, is The file not in The Download included?

//Pat

**Comment by ElGatoSaez** [comment]
Same. But this is happening to me with Spanish. ¿Thoughts?

**Comment by PJanisio** [comment]
Cant reproduce :/

**Comment by claudehohl** [comment]
@TME97: how can I reproduce it?

**Comment by claudehohl** [comment]
Duplicate: https://github.com/claudehohl/Stikked/issues/186

**Comment by TME97** [comment]
@claudehohl: i just installed the latest version, didn't changed the dir structure sind got this error

**Comment by claudehohl** [comment]
Can't reproduce too :( db_lang.php is in the core, which has been update ;)
just try it with the most recent master and reopen if the issue still persists.

**Comment by TME97** [comment]
Okay, i'll do.

Von meinem iPhone gesendet

**Comment by maop** [comment]
I just installed a new fresh 0.12.0 stikked and this message appeared.
I know why this happens, i did all the configuration at application/config/stikked.php as instructed, there i changed the language to 'spanish',  and choose sqlite as db backend but i forgot to create the db/  directory under htdocs. Then i tried to reload my stikked domain and got the db_lang.php error

So what is happening here is, codeigniter is trying to display an error message telling me it cannot create the database in the db/ directory, and this error message is declared at db_lang.php but is unable to find the spanish translation (as language setting is overwritten in config/stikked.php)

A workaround is to edit application/config/config.php and change language to 'english' so codeigniter look there for the default messages, and the stikked messages are still displayed in the chosen language.

**Comment by claudehohl** [comment]
Yea I think I'll revert this "intelligent language switcher" which causes too many sideeffects...
