### ISSUE TITLE
[Feature] Support Open Graph protocol

### ISSUE THREAD

**Issue by ngdinhtoan** [claudehohl/Stikked#267]
View page should support [OpenGraph protocol](http://ogp.me/).

**Comment by xZero707** [comment]
I support your recommendation. We'll see what owner thinks about it.
In my opinion, integration should be easy.

**Comment by The-Compiler** [comment]
After looking at the page above with @claudehohl recently, we both really don't get what's it about exactly.

Could you explain how this related to Stikked, and how it would be used - i.e. how it relates to a pastebin? What are the benefits of implementing this?

**Comment by xZero707** [comment]
OpenGraph protocol is very good for SEO, and for sharing link on social networks. Eg. it dictates Facebook how exactly to show link preview once when pasted.

If you take a look in source code of eg this Pastebin paste http://pastebin.com/Z4EXsCsm, in header there is:
```
            <meta property="og:title" content="[Bash] GitHub - Pastebin.com" />
	    <meta property="og:type" content="article" />
	    <meta property="og:url" content="http://pastebin.com/Z4EXsCsm" />
	    <meta property="og:image" content="http://pastebin.com/i/fb2.jpg" />
	    <meta property="og:site_name" content="Pastebin" />
```

Also, this is something search engine will easily catch once it comes to it.

**Comment by claudehohl** [comment]
SEO, Facebook, Google... *puke*

**Comment by xZero707** [comment]
However it is repulsive. for your, me or anyone, it's our reality, and we have to deal with it.

**Comment by claudehohl** [comment]
We deal with it by going forward as a good example by \*not* using it. Let's change reality and go back to a distributed web, shall we? :)

As @The-Compiler mentioned:

> Could you explain how this related to Stikked, and how it would be used - i.e. how it relates to a pastebin? What are the benefits of implementing this?

Closing for now.
