### ISSUE TITLE
Using different Captchas

### ISSUE THREAD

**Issue by Z3roCoder** [claudehohl/Stikked#268]
Is it possible to use different Captchas instead of the "type these letters into the box"?
I have once seen online such a captcha ala "click on the captcha to proof you are a human" - Which I absolutely love!

**Comment by Jay2k1** [comment]
That is Google's new reCaptcha. Support for this was added in https://github.com/claudehohl/Stikked/pull/245 and all you need to do is get yourself an API key at https://www.google.com/recaptcha/admin and copy the two key strings to your stikked.php config file in the captcha section.

**Comment by Z3roCoder** [comment]
Aah, very good thanks

Also, is there any reason why I have to do the captcha only once and then never again, as long as I dont clear my cache?

**Comment by claudehohl** [comment]
Comfort! Captchas are annoying, and you only have to prove once that you are human - it is stored in the session then and won't bother you again.

**Comment by Z3roCoder** [comment]
Is it opssible to disable this function and require captcha for every paste, like other paste sites do?

I mean, now with googles reCAPTCHA it is just a simple click anyway ;)

**Comment by Z3roCoder** [comment]
BTW I just noticed - Stikked uses a recaptcha where you just have to click.
Why do I have to choose a certain topic out of 8 provided pictures at my page? o.o

**Comment by claudehohl** [comment]
> Is it opssible to disable this function and require captcha for every paste, like other paste sites do?
Why would you want this? Also, I don't like running an obscure Google code besides my "create encrypted" function.
"Google implemented a whole VM in JavaScript with a specific bytecode language." https://github.com/neuroradiology/InsideReCaptcha

"Google servers will receive and process, at least, the following information:
Plug-ins
User-agent
Screen resolution
Execution time, timezone
Number of click/keyboard/touch actions in the <iframe> of the captcha
It tests the behavior of many browser-specific functions and CSS rules
It checks the rendering of canvas elements
Likely cookies server-side (it's executed on the www.google.com domain)
And likely other stuff..."

This is fucking evil and I want to minimize the risk as much as possible. Therefore, only display it once and then never run it again - for security reasons.

> BTW I just noticed - Stikked uses a recaptcha where you just have to click.
I didn't change anything in the captcha config. ReCaptcha decides which method it uses (or it's probably configurable, I haven't checked).

**Comment by Z3roCoder** [comment]
Very well, I understand. Thank you for your answers!
