### ISSUE TITLE
"Burn on reading" echo text

### ISSUE THREAD

**Issue by ThaMunsta** [claudehohl/Stikked#269]
If you select burn on reading as the expiration the echo text that shows the url will be on a blank page if you click create, and will replace the buttons on the same page if you create encrypted.

Personally I think the result when creating encrypted is better but ideally would show a text box similar to when you click show code next to the embed link. A bonus would be to display the QR code also.

**Comment by ThaMunsta** [comment]
Well, maybe not the QR code part. I just played around with that a bit and displaying that basically burns the post haha

**Comment by ThaMunsta** [comment]
Burn on reading pastes also seem to get cleaned by the CRON even if they have not been viewed. If your cron runs every minute that means they almost never get seen...

**Comment by claudehohl** [comment]
Oh that would be devastating. I'll check.

**Comment by PJanisio** [comment]
@ThaMunsta 

Now it shouldnt be so devastating with #270

**Comment by claudehohl** [comment]
Thanks!
