### ISSUE TITLE
404 with stikked NGINX, unable to get the web config example to work.

### ISSUE THREAD

**Issue by Skyrid3r** [claudehohl/Stikked#278]
The main page works just fine, but whenever I submit submit, view, etc something I'm getting a 404. Now, I've tried tons of nginx examples from the file I downloaded to to internet, and nothing appears to work. 

Seeing I'm using the IP address of the server for testing purposes, i already have a root address where all the directories are supposed to load. So with example:

server
{
        server_name .SERVER IP ADDRESS;
        listen SERVER IP ADDRESS;

        root /var/www/ipaddress/www;
        index index.php index.htm index.html;

        location ~* \.(php|php5|php4)($|/) {
                                fastcgi_param SERVER_PORT 80;
                                fastcgi_split_path_info ^(.+\.(?:php|php5|php4))(/.*)$;
                                if (!-e $document_root$fastcgi_script_name) {
                                                return 404;
                                }
                                include /xx/nginx/etc/fastcgi_params;
                                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                                fastcgi_pass unix:/xx/xx/.php.sock;
        }
}

So, if I for example try to add the location of the stikked path:

    location /stikked {
        try_files $uri /index.php;
    }

    location ~ \.php$ {
        return 444;
    }

or

location /stikked {
  try_files $uri $uri/ @stikked;
}
location @stikked {
  rewrite ^/stikked/(.*)$ /p/index.php?/$1 last;
}

But nothing appears to work.. Some help would be really nice.

**Comment by afritsch** [comment]
Same problem here (nginx+hhvm+mariadb). Might be a problem with stikked not liking to be installed in a subfolder? (but I never tried it on a subdomain)

**Comment by astoltz** [comment]
According to your example, you'd want: try_files $uri $uri/ /stikked/index.php;

**Comment by afritsch** [comment]
thanks, that did the trick. :thumbsup: would have never thought of that.
until now I've never encountered something where I had to prepend the subfolder to the try_files directive.

**Comment by afritsch** [comment]
I am stupid. The newest version (0.9.1 from the release page) breaks my setup again. I did not change the configuration. The landing page works fine, but recent and trending is broken again. Instead of a 404 I get now a 500 Server Error. No errors in the logs.

**Comment by claudehohl** [comment]
test the newest release (branch master). reopen if it still happens.

**Comment by humppa** [comment]
I've experienced this same issue (*nginx* returning 500, when accessing `/lists` or `/trends`). Using newest in master fixed it.

Thank you!

**Comment by claudehohl** [comment]
Yey! Great, thx!

**Comment by usr01** [comment]
Hi!
Same problem. Always receiving 404 in Create, Recent, Trending, API... even with the last version. 
Thanks
