### ISSUE TITLE
default_expiration ignored when disable_keep_forever is set to false

### ISSUE THREAD

**Issue by Sei-Lisa** [claudehohl/Stikked#279]
When setting `$config['disable_keep_forever']` to `false`, the value set in `$config['default_expiration']` is ignored. No matter how it's set, it will always default to "Keep Forever".

When `$config['disable_keep_forever']` is set to `true`, the `default_expiration` setting works as expected.

**Comment by claudehohl** [comment]
Can't reproduce.

Update from master branch and try again - if it's still an issue, please reopen.

**Comment by Sei-Lisa** [comment]
@claudehohl I can't reopen it, but it's still an issue with current head. The issue should be self-evident from line 105 here:

https://github.com/claudehohl/Stikked/blob/master/htdocs/themes/default/views/defaults/paste_form.php#L92

or 107 here:

https://github.com/claudehohl/Stikked/blob/master/htdocs/themes/bootstrap/views/defaults/paste_form.php#L93

The problem was introduced in commit b4291a1.

Reproduction steps:

1) Grab a fresh copy of `master`.
2) Rename `htdocs/application/config/stikked.php.dist` to `.../stikked.php`.
3) Edit config, set the database parameters appropriately and set:
```
    $config['disable_keep_forever'] = false;
    $config['default_expiration'] = 10080; // or some other valid value other than 0
```
4) Ensure you're using the default theme.
```
    $config['theme'] = 'default';
```
5) Go to the form to post a stikked, and observe the "Delete After" field set to "Keep Forever", as the code sets it (unless maybe you're refreshing a previous page, in which case the browser may enforce keeping the previous values, so be sure to use a fresh page and not an existing one).
6) Comment out line 105 in `htdocs/themes/default/views/defaults/paste_form.php` and observe the issue disappear.

**Comment by demonicpagan** [comment]
I concur that this issue is present. The only way posts expire is if disable_keep_forever is set to true and I lose the option to keep posts forever which I want as my default unless otherwise selected.
