### ISSUE TITLE
remove_invisible_characters removing legitimate paste content.

### ISSUE THREAD

**Issue by fmichea** [claudehohl/Stikked#28]
Hi guys,

I installed and started using your pastebin last week, and today we noticed that some legitimate content (example bellow) was removed.  I looked in the code and think it's due to remove_invisible_characters[1] removing HTML special charaters pasted in hexadecimal (I think).

Is this a feature? Could it be something wrong in my configuration? Is there a work arround?

Example (C code):
```c
int main(void)
{
    // When pasted, only "s" remains as the format string.
    printf("%12s", "I am a string");
    return 0;
}
```

I am sorry if it is not the right place for this. Thank you in advance.

[1] https://github.com/claudehohl/Stikked/blob/master/htdocs/system/core/Common.php#L514

**Comment by claudehohl** [comment]
test it with CI 3.0

**Comment by claudehohl** [comment]
tested with ci 3, works.
