### ISSUE TITLE
Without Captcha can create encrypted pastes 

### ISSUE THREAD

**Issue by abbaselmas** [claudehohl/Stikked#280]
I am not sure if it is supposed to be this way or not but

when you use "create encrypted" you can bypass "I am not a rebot" captcha.

I have created this paste without verifying that I am not a robot http://paste.scratchbook.ch/view/cc653898#ntjGQVqBOXIWbrPFaEZw64dvCOsma43I

**Comment by xZero707** [comment]
I have reproduced issue. Confirmed.

**Comment by claudehohl** [comment]
It's not an issue, since encrypted pastes won't show up in the recents. And I haven't seen a machine executing javascript. why would an advertiser anyway spam my pastebin with encrypted data?
