### ISSUE TITLE
[Featurerequest] Let users change theme via dropdown

### ISSUE THREAD

**Issue by afritsch** [claudehohl/Stikked#282]
Currently the selected theme is hard-set for everybody in the stikked config.
Would it be possible to implement a simple dropdown-menu (e.g. somewhere on the bottom) to let the users change their preferred theme and save it via cookie? (this setting would override the one set in the stikked config)

**Comment by xZero707** [comment]
Good idea. If owner agree that it should be implemented, I would work on it.

**Comment by PJanisio** [comment]
Well its better to implement language choosing by dropdown, pretty easy while the lang can be set by $_GET.

I would rather left theme to be chosen by the owner.

**Comment by xZero707** [comment]
Both can be implemented. Even better, Stikked should automatically chose best language for visitor.

Theme choice - Major bulletin boards, like IPB, MyBB, phpBB offers user a choice of theme, based on administrator setting. Same should be implemented to Stikked,

So, let the owner chose: Offer user ability to change theme + Setup a default theme for new visitors
 
I still think that registration/login system should be implemented, that would be good base for user customization.

**Comment by PJanisio** [comment]
Stikked arleady should automatically recognize and set language of visitor. But if you are travelling than it will not work :-)

**Comment by xZero707** [comment]
Yes, and that's why there should be choice as well. I always hated websites and applications which force whatever language based on my location.
Eg. I live in Sweden, but I'm not originally from Sweden and I'm not here long enough to learn Swedish but some apps online or offline are forcing me to use Swedish....

**Comment by claudehohl** [comment]
That would make Stikked more stuffed. I don't know how useful it is... For now, it's a lower priority to me.

**Comment by xZero707** [comment]
I agree.
