### ISSUE TITLE
How to remove capatcha?

### ISSUE THREAD

**Issue by OurSickStory** [claudehohl/Stikked#283]
no way to contact, close this asap.

**Comment by claudehohl** [comment]
wat?

**Comment by OurSickStory** [comment]
The heading is a whole bunch of lies.
But running ubuntu 14.04. Everythings installed as instructed;
http://inutile-gaming.com/Stikked/htdocs/
followed both guides on changing .htaaccess and
"	<Directory "Stikked/htdocs">
		Options +FollowSymLinks
		AllowOverride All
		Order allow,deny
		Allow from all
	</Directory>"
Still can't see the other pages; http://inutile-gaming.com/Stikked/htdocs/lists etc, any idea?

**Comment by xZero707** [comment]
Do you have mod_rewrite enabled on your server?

**Comment by OurSickStory** [comment]
root@invoke:~# sudo a2enmod rewrite
Module rewrite already enabled
root@invoke:~#

yes sir.

**Comment by claudehohl** [comment]
> no way to contact, close this asap.

kthxbai.
