### ISSUE TITLE
[question] Encrypted RAW pastes ALWAYS encrypted?

### ISSUE THREAD

**Issue by AdrianKoshka** [claudehohl/Stikked#284]
**As far as I know and have tested** I can not view the unencrypted version of a paste if I use try to view it in RAW, is this an issue with Stikked or how a RAW paste is formatted?

E.g. : http://paste.scratchbook.ch/view/raw/1427473f#iP7p05DRH0BC72qQjxv01BjUeOmNV073

**I can only see the encrypted version of this RAW paste as I stated above.** As I'm not familiar with PHP and/or JavaScript at the moment I don't know where the responsible code is for encrypting or how the encrypting is done. If someone could point out the section of code responsible for handling encrypion to me and/or explain what encryption method/standard Stikked is using that would also be helpful.

**Comment by claudehohl** [comment]
Well, "raw" means plaintext without any javascript to decode the encryption. view:source ;-)

**Comment by AdrianKoshka** [comment]
Thanks for the answer. How would one go around decrypting the RAW paste(is that possible on client side without adding to the API)??

**Comment by claudehohl** [comment]
> How would one go around decrypting the RAW paste

by removing the _/raw_ in the URL.

**Comment by AdrianKoshka** [comment]
> by removing the /raw in the URL.

While yes this works if you are using the web interface it does not work if you are trying to use the API.

E.g. `curl http://paste.scratchbook.ch/view/1427473f#iP7p05DRH0BC72qQjxv01BjUeOmNV073`

only spits out the page(the paste does not even decrypt the paste!). [gist linked here](https://gist.github.com/AdrianKoshka/c401062543115ea6605b)

I am assuming this is due to either operator error (me doing something wrong) or a lack of feature in the API. so for now I don't consider

> by removing the */raw* in the URL.

an adequate  answer. I am not trying to be a thorn in your side I am just trying to understand how the API works with encryption thus far(which from what I understand from #243 this might be in the works and the API isn't even equipped to deal with encryption/decryption **IF** possible.).

**Comment by claudehohl** [comment]
No, unfortunately not, the encryption is done via JavaScript and the API is purely text-based/commandline...

**Comment by The-Compiler** [comment]
I think the only good answer to this issue is having a good commandline-client which also supports encrypted pastes and decrypts them. I'll look at it somewhen in the future, but right now I'm busy with stuff which is more important to me.

**Comment by xZero707** [comment]
@claudehohl Why we wouldn't implement that part of encryption into PHP? At least for API, and RAW.

**Comment by The-Compiler** [comment]
Probably because if you transmit the key to the server and the server decrypts things for you, you could also just not encrypt it in the first place :wink:

**Comment by xZero707** [comment]
Your statement is not clear for me. Please explain.

**Comment by The-Compiler** [comment]
The whole point of encryption is that it happens client-side - i.e. the server will never know the contents of your paste.

If you send the key to the server and do decryption there, it's pointless, because if the server knows your decryption key (the thing after the `#` in the URL), you could as well just do an unencrypted paste.

**Comment by xZero707** [comment]
Well I cannot agree nor completely disagree with you, server is not living being which will just remember key on it's own. 

It's AES, it doesn't need saved key to be compared to, only supplied key, for what is enough just single $_GET or $_POST so key doesn't have to be saved.

Eg. I have web application which keeps user files in encrypted format, and encryption key is available only on client side, but not saved on server in any form. However Encryption/Decryption is done on server. 
There is no simple way for me or any of administrators to decrypt users files nor know their keys. 


But I cannot completely disagree: it's more secure that encryption is done only on client side, so there is no data transmission and therefore no way of man-in-the-middle attack, but if site uses SSL, security is on very good and acceptable level.

**Comment by AdrianKoshka** [comment]
Thank you @claudehohl for clarifying that the encryption is done via JS. Which I guess means unless someone built a client-side JS application(I think that'd be the right work in this case) to handle en/decrypting it wouldn't be possible as of now. If anyone feels this issue should be closed feel free as I've gotten pretty much what I wanted to know.
