### ISSUE TITLE
[Feature] Integrate the tool with a compiler

### ISSUE THREAD

**Issue by boblatino** [claudehohl/Stikked#287]
I will like to integrate your amazing tool with gcc and pipe the errors and run messages to a window. Do you think its feasible? If so I can help to implement the feature but I will need at least some advice on how to add a new button (say "build and run") next to the "create encrypted" that will call create and then forward the page to a "console view" which will show in real time the compile and run of the app.

Thanks

**Comment by xZero707** [comment]
Wouldn't it be better to have client app which can connect to any server powered by Stikked?

**Comment by The-Compiler** [comment]
I'm not sure if it makes sense to shoehorn this into Stikked, to be honest. Why not use one of the existing projects? I remember having seen a few services, I'm sure there's also a thing you can host yourself somewhere.

**Comment by claudehohl** [comment]
Well Stikked is not meant for realtime output... Closing.

**Comment by claudehohl** [comment]
Btw, "shoehorn", I like that term! :D
