### ISSUE TITLE
No error when php can't find appropriate db libraries

### ISSUE THREAD

**Issue by allyunion** [claudehohl/Stikked#289]
My php database modules were not installed so I kept getting a blank page.  And the program didn't report back the functions were invalid...

**Comment by xZero707** [comment]
Possibly you don't have error reporting enabled on your server? That's common default setting for production environment.

**Comment by allyunion** [comment]
no, I had it enabled.  I was using nginx + php-fpm, and it reported no
errors anywhere.

**Comment by claudehohl** [comment]
blank page often happened in CI 2.x. Update to newest master and see if it gives still a blank page. reopen issue then.
