### ISSUE TITLE
[Featurerequest] Remove cron in favor of removing pastes based on user visits

### ISSUE THREAD

**Issue by allyunion** [claudehohl/Stikked#291]
The idea behind this is that based on the frequency of traffic of visits, would a cronjob be necessary?  Shouldn't all attempts to remove pastes happen on every visit?  Is that too aggressive?

**Comment by mrc0mmand** [comment]
That could cause several problems (like (D)DoS) in case of huge traffic - for each visitor another SQL query would need to be run (and even worse - it could be triggered manually). And that can take considerable amount of time on huge databases. 
Also, in my opinion, it doesn't even make much sense - why would you want to run SQL cleanup query dozens of times per second (in worst case) instead once per, let's say, minute? On low-traffic instances this wouldn't cause any significant problems, but it would be an issue for the high-traffic ones.

**Comment by claudehohl** [comment]
Yes, I agree with @mrc0mmand. Too aggressive, closing...
