### ISSUE TITLE
unexpected T_OBJECT_OPERATOR

### ISSUE THREAD

**Issue by gthorne** [claudehohl/Stikked#292]
I've been banging my head against this for the better part of the day, and I'm hoping someone can point out where I've gone wrong.  I'm experienced with CodeIgniter and Apache configs, but I'm obviously missing something simple somewhere.

I can get to the front page, but the screen goes blank when I paste, and the 'recent' and 'trending' links lead to blank pages as well.

I'm running ours as a vhost on our corporate webserver (I'll santize the URLs with 'mycorp' in the examples below).

Here's the relevant vhost entry:

    <VirtualHost *:80>
        ServerName sticky.mycorp.us
        DocumentRoot /var/www/html/sticky
        ErrorLog logs/sticky.mycorp.us-error_log
        CustomLog logs/sticky.mycorp.us-access_log common
            <Directory />
                    AllowOverride All
            </Directory>
    </VirtualHost>

And here's what shows up in the logs when I click the 'Recent' link (including a rewrite.log I set up for debugging):

    ==> /tmp/rewrite.log <==
    10.1.98.248 - - [14/Aug/2015:05:31:53 +0000] [sticky.mycorp.us/sid#7efefe5db2f0][rid#7efefe968bb8/initial] (3) [perdir /var/www/html/sticky/] strip per-dir prefix: /var/www/html/sticky/lists -> lists
    10.1.98.248 - - [14/Aug/2015:05:31:53 +0000] [sticky.mycorp.us/sid#7efefe5db2f0][rid#7efefe968bb8/initial] (3) [perdir /var/www/html/sticky/] applying pattern '^(.*)$' to uri 'lists'
    10.1.98.248 - - [14/Aug/2015:05:31:53 +0000] [sticky.mycorp.us/sid#7efefe5db2f0][rid#7efefe968bb8/initial] (4) [perdir /var/www/html/sticky/] RewriteCond: input='lists' pattern='!^(index\\.php|static|favicon\\.ico|robots\\.txt|sitemap.xml|google(.+)\\.html)' => matched
    10.1.98.248 - - [14/Aug/2015:05:31:53 +0000] [sticky.mycorp.us/sid#7efefe5db2f0][rid#7efefe968bb8/initial] (2) [perdir /var/www/html/sticky/] rewrite 'lists' -> 'index.php?/lists'
    10.1.98.248 - - [14/Aug/2015:05:31:53 +0000] [sticky.mycorp.us/sid#7efefe5db2f0][rid#7efefe968bb8/initial] (3) split uri=index.php?/lists -> uri=index.php, args=/lists
    10.1.98.248 - - [14/Aug/2015:05:31:53 +0000] [sticky.mycorp.us/sid#7efefe5db2f0][rid#7efefe968bb8/initial] (3) [perdir /var/www/html/sticky/] add per-dir prefix: index.php -> /var/www/html/sticky/index.php
    10.1.98.248 - - [14/Aug/2015:05:31:53 +0000] [sticky.mycorp.us/sid#7efefe5db2f0][rid#7efefe968bb8/initial] (2) [perdir /var/www/html/sticky/] strip document_root prefix: /var/www/html/sticky/index.php -> /index.php
    10.1.98.248 - - [14/Aug/2015:05:31:53 +0000] [sticky.mycorp.us/sid#7efefe5db2f0][rid#7efefe968bb8/initial] (1) [perdir /var/www/html/sticky/] internal redirect with /index.php [INTERNAL REDIRECT]
    10.1.98.248 - - [14/Aug/2015:05:31:53 +0000] [sticky.mycorp.us/sid#7efefe5db2f0][rid#7efefe7a42d0/initial/redir#1] (3) [perdir /var/www/html/sticky/] strip per-dir prefix: /var/www/html/sticky/index.php -> index.php
    10.1.98.248 - - [14/Aug/2015:05:31:53 +0000] [sticky.mycorp.us/sid#7efefe5db2f0][rid#7efefe7a42d0/initial/redir#1] (3) [perdir /var/www/html/sticky/] applying pattern '^(.*)$' to uri 'index.php'
    10.1.98.248 - - [14/Aug/2015:05:31:53 +0000] [sticky.mycorp.us/sid#7efefe5db2f0][rid#7efefe7a42d0/initial/redir#1] (4) [perdir /var/www/html/sticky/] RewriteCond: input='index.php' pattern='!^(index\\.php|static|favicon\\.ico|robots\\.txt|sitemap.xml|google(.+)\\.html)' => not-matched
    10.1.98.248 - - [14/Aug/2015:05:31:53 +0000] [sticky.mycorp.us/sid#7efefe5db2f0][rid#7efefe7a42d0/initial/redir#1] (1) [perdir /var/www/html/sticky/] pass through /var/www/html/sticky/index.php
    
    ==> /var/log/httpd/sticky.mycorp.us-error_log <==
    [Fri Aug 14 05:31:53 2015] [error] [client 10.1.98.248] PHP Parse error:  syntax error, unexpected T_OBJECT_OPERATOR in /var/www/html/sticky/application/models/pastes.php on line 466, referer: http://sticky.mycorp.us/
    
    ==> /var/log/httpd/sticky.mycorp.us-access_log <==
    10.1.98.248 - - [14/Aug/2015:05:31:53 +0000] "GET /lists HTTP/1.1" 500 20
 
I don't see any other mentions of this T_OBJECT_OPERATOR, and the code on line 466 looks good.  My prefix is still the default empty string.  So, I suspect the problem is somewhere in my config.

**Comment by gthorne** [comment]
Ok, I must have messed something up on the install.  I deleted the entire directory, and re-installed (using the same stikked.php conf file), and it works now.  I'll leave this open if you want to provide a solution for other users that are using this.

**Comment by CodeBrauer** [comment]
seems that #235 is related to that.

I also had this problem and the code in the last release has a bug:
https://github.com/claudehohl/Stikked/blob/40a22a46868a1c29b003b0e03c5fa8c7d234579b/htdocs/application/models/pastes.php#L466

It is fixed by replacing that line with: 
```php
$sql = "SELECT id FROM $TABLE WHERE private = 0 AND (title LIKE ? OR raw LIKE ?)";
```

The orginal source can't even work - https://3v4l.org/tvHKI

**Comment by xZero707** [comment]
@CodeBrauer Why don't you make pull request with your fix?

**Comment by CodeBrauer** [comment]
@xZero707, The wrong line is only The latest release, in master-branch it's already fixed - so they need to make a New release.

**Comment by xZero707** [comment]
Ah, ok, understand. That's on @claudehohl  then.

**Comment by claudehohl** [comment]
Jup. I have planned to work on Stikked next week, release is scheduled at the end of September.
