### ISSUE TITLE
API Random returns private pastes

### ISSUE THREAD

**Issue by mzac** [claudehohl/Stikked#295]
When you post a private paste, they won't show up in recent, however they do show up with the api/random url

**Comment by xZero707** [comment]
Confirmed.
![3243refdgdrwe33333d](https://cloud.githubusercontent.com/assets/3281104/9366088/84dd5ede-46b5-11e5-9eb4-9a1921aed9d6.png)

**Comment by xZero707** [comment]
Fixed by now.

**Comment by claudehohl** [comment]
Jup, thanks!
