### ISSUE TITLE
Blank page and CodeIgniter

### ISSUE THREAD

**Issue by majk-p** [claudehohl/Stikked#297]
I've just set up stikked and I'm getting blank page. After changing settings to development, I got an error:

    A PHP Error was encountered
    Severity: Notice
    Message: Only variable references should be returned by reference
    Filename: core/Common.php
    Line Number: 257

That refers to:

    return $_config[0] =& $config;

But fix found at [StackOverflow](http://stackoverflow.com/a/28348880/2040487):

    $_config[0] =& $config;
    return $_config[0]; 

Leeds only to another blank page. 

I'm running Apache, php 5.6.7, latest Stikked and MariaDB

**Comment by claudehohl** [comment]
Oh damn, a bug in the CodeIgniter core...

**Comment by claudehohl** [comment]
fixxorized with CI 3.x, harr
