### ISSUE TITLE
Database error with latest commit

### ISSUE THREAD

**Issue by xZero707** [claudehohl/Stikked#300]
http://paste.elite7hackers.net/
![fireshot capture 3 - database error - http___paste elite7hackers net_](https://cloud.githubusercontent.com/assets/3281104/9627866/5bf319e8-5167-11e5-8fc3-bd0db5c8e704.png)

Commit: Latest from your repo

**Comment by xZero707** [comment]
Possibly something new with Ci-3 which version before didn't have... Probably table creation will fix the issue, but even then we have to update upgrader to make it upgrade other people's databases as well.
Waiting for issue to be confirmed.

**Comment by claudehohl** [comment]
Gnah, I create the sessions table in the main.php controller. However it seems that this is not early enough :(
Let's see how I can fix this.

**Comment by claudehohl** [comment]
git pull ;)

**Comment by xZero707** [comment]
It's all good now, tnx! :+1:  :)
