### ISSUE TITLE
Can't fix single line word wrap

### ISSUE THREAD

**Issue by f07gano** [claudehohl/Stikked#302]
Hello, I have been trying to figure out how I can fix the word wrap for single lines of plain text. I tried changing individual themes to break-word in the css, but this doesn't change anything.
An example paste is here: http://halcyon-zj.com/paste/view/4368bcf8

I would like for the string to be cut into multiple lines to fit nicely into the box.

**Comment by xZero707** [comment]
For the class container add following css: word-wrap: break-word;
However better approach would be to set overflow: scroll; instead.

**Comment by f07gano** [comment]
Thank you very much! The scroll worked perfectly!

**Comment by xZero707** [comment]
:+1:
