### ISSUE TITLE
"Recent" and "trending" not working when browser requests other language than english

### ISSUE THREAD

**Issue by afritsch** [claudehohl/Stikked#304]
I just installed stikked from master. After fixing some initial issues config-wise, I encountered this error:
![stikked_lang](https://cloud.githubusercontent.com/assets/497652/9839407/8a95e5da-5a79-11e5-99c5-a183c22371ff.PNG)
When I changed in Chrome the primary requested language to english it works. This issue might also affect other localisations.

**Comment by claudehohl** [comment]
Ok, thanks for the report. Investigating...
