### ISSUE TITLE
combine_assets breaks https

### ISSUE THREAD

**Issue by fasterit** [claudehohl/Stikked#308]
Serving http and https out of the same http_root will lead to static/asset/*.css containing http:// or https:// depending on which call compiled the *.css combined_asset file.

In the http-case this will then break later https://stikked.tld renderings because it includes "unsafe" content via http.

Sample:

    [class*=" icon-"]:last-child{*margin-left:0}.icon-white{background-image:url("https://stikked.tld/themes/bootstrap/css/../images/glyphicons-halflings-white.png")}

**Comment by claudehohl** [comment]
It seems carabiner (the combine_assets library) doesn't take http and https into account. Generate all minified files for https:

1. set the base_url in htdocs/application/config/config.php to https://[your-domain]/
2. delete all the files in htdocs/static/asset/*
3. reload the page

It's all https. Mixed content in http doesn't matter, and under https, it's all https.

**Comment by fasterit** [comment]
That is not a solution because the https certificate is not necessarily signed with a (paid for) certificate the browser accepts. So in the case of locally signed or self-signed certificates your proposal will produce https cert warnings or not loaded element depending on the browser engine.
This should be fixed proper.

**Comment by claudehohl** [comment]
> That is not a solution because the https certificate is not necessarily signed with a (paid for) certificate the browser accepts. So in the case of locally signed or self-signed certificates your proposal will produce https cert warnings or not loaded element depending on the browser engine.

Well that's not my problem if you use a self-signed cert... I'm responsible for Stikked, not for the webserver environment.

**Comment by fasterit** [comment]
ehem, yes.

So for others that run into the same issue:

The upstream project carabiner "is not in active development" (from https://github.com/tonydewan/Carabiner), so getting it fixed upstream seemed not a likely option (we didn' try as it means quite a substantial change from the simple "write md5-filenames and read whatever is the latest *.{js|css}" logic the library currently uses).

So let's just outline the potential "solutions" for others that stumble upon the same issue:

A) duplicate http_root (DocumentRoot). So have the same files in (say) /var/www/plain and /var/www/ssl so that /var/www/{plain,ssl}/static/asset can contain the same files (carabiner creates the same filenames even though the content is different) without conflicting

B) Put something like:
```php
if (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] = 'on')
{
    $this->carabiner->config(array(
        'cache_dir'  => 'static/asset-secure/',
));
}
```
(in the coding style of stikked)
into each of themes/\*/views/defaults/headers.php and themes/\*/views/view/embed.php
So two per theme and ten changes in total with the five default styles supplied (yes there is a lot of redundancy in stikked's code).

C) fix the URLs in the generated *.css files to not contain the protocol (remove http/https to leave just // so the loading gets protocol agnostic).

**Comment by claudehohl** [comment]
Thanks for the detailed description!
