### ISSUE TITLE
0.10 issue Call to undefined method CI_Input::method()

### ISSUE THREAD

**Issue by jayze** [claudehohl/Stikked#313]
When creating a new paste (not encrypted) I run in this error. 

Downloaded the tar.gz from the "tag" and done as instructed.

Any idea on  how to fix it ?

Thanks.

**Comment by jayze** [comment]
Nobody had this issue ?

**Comment by idk** [comment]
Updated to 0.10.0 from 0.9.0 and now get this error when try to submit a paste.

**Comment by claudehohl** [comment]
I can't reconstruct it... reopen if this error still persists.
