### ISSUE TITLE
SSL - bg-x.png loaded through http

### ISSUE THREAD

**Issue by sjau** [claudehohl/Stikked#315]
Hi there

I just got accepted into Let's Encrypt Beta. So I did submit my pastebin domain, which can be accessed now through https://paste.simplylinux.ch

The problem is, the green padlock (in Chromium) doesn't appear because the bg-x.png image is still loaded through http instead of https.

The main.css file has this:
```
        background-image: url('../images/bg-x.png');
```
So it should be loaded - IMHO - through https but it's not.

Any suggestion?

**Comment by claudehohl** [comment]
your file is loaded through https, as far as I see...

baseurl needs to be provided with the new CI version, so this issue might really be a thing of the past.

**Comment by sjau** [comment]
I did manually change it. By default it didn't load that through https.

**Comment by claudehohl** [comment]
Oh, actually I can reconstruct it. Will test it with CI 3 and a fixed base_url and fix it if it still persists.

**Comment by claudehohl** [comment]
works with my newest additions ;) (dev-branch). you need to set the base-path (to https), and its all fine. those changes will be merged into master soon, hold on.

**Comment by sjau** [comment]
thx :) I think I should update my installation :)
