### ISSUE TITLE
Unable to find the language

### ISSUE THREAD

**Issue by monsdar** [claudehohl/Stikked#319]
When I try to access stikked I get the following message:

    Unable to load the requested language file: language/german/db_lang.php

I installed a fresh copy of Stikked 0.10.0 on my system. I changed the stikked.php to use sqlite and disabled Captcha. There are no db_lang.php files in any of the language-directories.

**Comment by monsdar** [comment]
I was able to solve the problem by using a MySQL-database. It seems to be a problem with the sqlite-support.

**Comment by claudehohl** [comment]
german translation for database errors is not provided (by codeigniter). i added it.

https://github.com/claudehohl/Stikked/commit/3683719343a021cad9b9a836093b935eae92b08d
