### ISSUE TITLE
Encrypted pastes broken on stikkedizr

### ISSUE THREAD

**Issue by SimonSickle** [claudehohl/Stikked#328]
For whatever reason, pastes are not decrypting on the stikkedizr theme. For an example see https://paste.teamblueridge.org/view/ad95b679#pTGVuRVhegVQsTyFN8z4eVAl8qkhBw9j

**Comment by SimonSickle** [comment]
Looks like theres a footer error too. I set that site back to bootstrap

**Comment by Pe46dro** [comment]
I have the same issues

Footer error:
```log
An Error Was Encountered

Unable to load the requested file: themes/default/views/stikkedizr/footer.php
```

**Comment by nickwinn** [comment]
Yup, can confirm this is a legit issue with this theme. Any idea on how to fix this? I love the stikkedizr theme otherwise.

**Comment by claudehohl** [comment]
selector for the container to decrypt was different, i added the elements. not the shiny solution, but it works for now without messing too much things up.
