### ISSUE TITLE
Feature Request - Edit Pastes

### ISSUE THREAD

**Issue by LOTRg** [claudehohl/Stikked#333]
is it possible to have edit and delete for pastes ? 
Is it possible to allow Images inline with pastes ( for example for Screenshots errors, display issues and anywhere else )

**Comment by kylelaker** [comment]
At least the first part of this will probably require implementation of #277 in order to ensure that the original creator is the one editing and deleting.

**Comment by claudehohl** [comment]
duplicates https://github.com/claudehohl/Stikked/issues/277, closing...
