### ISSUE TITLE
Feature: Sort by language

### ISSUE THREAD

**Issue by tyrollins** [claudehohl/Stikked#348]
Is it possible to sort the recent and trending pastes by language? (example - an option for users to select "html" and see all trending or recent "html" pastes.)

If not currently possible, anyone have a suggestion on how to implement? 

Cheers.

**Comment by claudehohl** [comment]
Well it's possible, acts like a filter. I would need to create a dropdown with all languages for filter selection and apply it then.

**Comment by tyrollins** [comment]
I personally think it would be a great feature. I'm still a bit early in my php journey, but hopefully I can lend a hand with some of this soon. 

Quick off topic question - Any plans to integrate a login system so users could keep track of their snippets? Might be easier with github oauth?

**Comment by claudehohl** [comment]
Yes. https://github.com/claudehohl/Stikked/issues/277
