### ISSUE TITLE
Captcha inconsistency

### ISSUE THREAD

**Issue by tbs** [claudehohl/Stikked#350]
The captcha config is set to use _reCaptcha_, but it is displaying internal captcha sometimes. Not sure how to replicate this issue, all I know is if I sent a paste, keep tab open in my browser for some days, my router get new ip or whatever, I check the tab and there is the internal captcha visible if I want to send a "reply" to this paste.

![aks 1](https://cloud.githubusercontent.com/assets/768954/14232836/28d3b9f4-f98d-11e5-8295-ede1cfa6c2a1.png)

I was expecting to see only **reCaptcha**.

**Comment by The-Compiler** [comment]
I've seen this before as well.

**Comment by claudehohl** [comment]
When a paste contains sensitive information (private checkbox selected, or encrypted pastes), all google code is disabled and the internal captcha displayed as a fallback.

https://github.com/claudehohl/Stikked/blob/master/htdocs/application/controllers/Main.php#L627-L630

https://github.com/claudehohl/Stikked/blob/master/htdocs/themes/default/views/defaults/paste_form.php#L120

I dunno why keeping a tab open for some days triggers the fallback.
