### ISSUE TITLE
Pastes Not Expiring

### ISSUE THREAD

**Issue by tundratim** [claudehohl/Stikked#355]
For some reason, when I post via API (not checked on interactive site), the paste does not get expired but just hangs out forever claiming it's going to disappear in 1 second.  Syntax is:

curl -d title="mytitle" -d name="myname" -d expire=5 --data-urlencode text@myfile  http://.../api/create/?apikey='mykey'

The post appears just fine, it just never ages into extinction.  If I say use -d expire="burn" instead, that works as expected.

Is there a problem with my syntax or is this a known issue?

**Comment by The-Compiler** [comment]
So it works for pastes pasted via the webinterface, i.e. you have your cronjob set up correctly?

**Comment by tundratim** [comment]
D'Oh, that was it.  Grrrrrr.  Issue closed
