### ISSUE TITLE
404 error removing htdocs

### ISSUE THREAD

**Issue by iamrohan14** [claudehohl/Stikked#357]
i dont want htdocs folder,
so i copied all the files from that folder to main root .
but not only index page is opening another pages are giving
"Not Found

The requested URL /lists was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request."

I want to run the project from direct root not from htdocs because after creating paste htdocs folder comes in the url

**Comment by Lartza** [comment]
A bit late but if you do mv htdocs/* and then rm -rf  htdocs you are missing the .htaccess file in the root folder and if you are using Apache, that means you have no rewrites in place for /lists etc
