### ISSUE TITLE
PHP 7.0: "Methods with the same name" PHP Error

### ISSUE THREAD

**Issue by war59312** [claudehohl/Stikked#359]
Hi,

Thought I'd test with PHP 7.0 via:

>  # Enable PHP 7.0
> AddType application/x-httpd-php70 .php
> SetEnv PHPRC /home

Sadly this is displayed on all pages now:

> A PHP Error was encountered
> Severity: 8192
> Message: Methods with the same name as their class will not be constructors in a future version of PHP; GeSHi has a deprecated constructor
> Filename: geshi/geshi.php
> Line Number: 259

File Path:

> /application/libraries/geshi/geshi.php

So back to PHP 5.6 for now.

Thanks,

Will

**Comment by claudehohl** [comment]
Ouch! :D Well then...
Thanks for testing!

**Comment by claudehohl** [comment]
Hmm, I have php7 on my debian testing as well and I get none of these errors...
