### ISSUE TITLE
New Go CLI client with client side encryption support

### ISSUE THREAD

**Issue by tcolgate** [claudehohl/Stikked#360]
Hi,
  Just a quick heads-up to mention that I've put together a Stikked client in Go that supports the native cryptjs/lzjs based encryption used in the default themes. The client is at:

[http://github.com/tcolgate/gostikkit](http://github.com/tcolgate/gostikkit)

  Feel free to mention it on the list of clients if you like.

**Comment by claudehohl** [comment]
Oh my god oh my god oh my god. You just made me really happy. About a week ago, I (re)discovered Go; this time, it really hit my awesomeness-detector-triggers big. The more talks I watched, the more thrilled I became. Now I'm at the point of "ok, I need a first little project to get my hands dirty."

Now here comes your pull request. Right now. This is a double-headshot single strike oneshot Tango down epicwin.

mind=blown.

Now I have some Go code that's not too complex and works in a familiar environment.

Thank you so much!

**Comment by claudehohl** [comment]
Done. https://github.com/claudehohl/Stikked/commit/f20e7db126927aa788dd211e03cacea80e368cdf
