### ISSUE TITLE
Markdown Syntax

### ISSUE THREAD

**Issue by blog2read** [claudehohl/Stikked#361]
Is there any idea to support texts with **Markdown syntax**? Would be cool - thanks.

**Comment by Thomas131** [comment]
yes, that would be cool. I just wanted to ask for exactly the same thing!

**Comment by claudehohl** [comment]
No Markdown support in Geshi (the syntax highlighter, see http://qbnz.com/highlighter/)...

Too bad. Isn't there a syntax highlighter in PHP that is current and maintained? Sigh.

**Comment by CompuRoot** [comment]
Could you please take a look at https://github.com/erusev/parsedown. Pretty decent and well supported product IMHO. It used in well known projects. 
Fork of original [PasteBin](https://github.com/jordansamuel/PASTE) using it together with Geshi as 

    // Apply syntax highlight
    $p_content = htmlspecialchars_decode($p_content);
    if ( $p_code == "markdown" ) {
        include( $parsedown_path );
        $Parsedown = new Parsedown();
        $p_content = $Parsedown->text( $p_content );
    } else {
        $geshi     = new GeSHi($p_content, $p_code, $path);
        $geshi->enable_classes();
        $geshi->set_header_type(GESHI_HEADER_DIV);
        $geshi->set_line_style('color: #aaaaaa; width:auto;');
        $geshi->set_code_style('color: #757584;');
        if (count($highlight)) {
            $geshi->enable_line_numbers(GESHI_NORMAL_LINE_NUMBERS);
            $geshi->highlight_lines_extra($highlight);
            $geshi->set_highlight_lines_extra_style('color:#399bff;background:rgba(38,92,255,0.14);');
        } else {
            $geshi->enable_line_numbers(GESHI_FANCY_LINE_NUMBERS, 2);
        }
        $p_content = $geshi->parse_code();
        $style     = $geshi->get_stylesheet();
        $ges_style = '<style>' . $style . '</style>';
    }
so I guess it wouldn't be hard to use both parsers in the same time.
 

By the way, Geshi is still in business (last update May, 2017) and [support PHP7](http://qbnz.com/highlighter/news.php?id=135)
