### ISSUE TITLE
404 and CSS errors - rewrite running

### ISSUE THREAD

**Issue by six86** [claudehohl/Stikked#368]
I just can't get it to work.

I checked out stikked to /var/www/stikked

I added the following entry to an existing vhost:

~~~
<Directory "/var/www/stikked/htdocs">
                RewriteEngine on
                LogLevel alert rewrite:trace6
                Options +FollowSymLinks
                AllowOverride All
                Order allow,deny
                Allow from all
</Directory>
~~~

The index page loads and I can add entries, but when viewing the CSS gets mixed up and links are pointing to wrong addresses. 

I tried around with the RewriteBase etc. but after two hours I just can't get it to work.

Originally I wanted to run stikked under "domain.com/pastebin" but I can't even get it to work as it is.

What am I doing wrong?!

**Comment by maxwave** [comment]
Same issue here... It's looking for files under view/theme/default

**Comment by maxwave** [comment]
@six86 I got mine working. Added a value for $config['base_url'] in application/config/config.php. I hope that helps.

**Comment by six86** [comment]
Thx @maxwave . Now the links are correct and the thing is working. But I still have no CSS so it looks very bad. The system is looking for this stylesheet:

~~~
/static/asset/1467818695af9c4884aaa89b249e8c4a2e366f107b.css
~~~

But the folder only contains a .keep file (I assume for git...).

**Comment by six86** [comment]
Ok solved it. Was a acces rights issue. The folder `static/asset` has to be writable for the web server user (in my case www-data for apache).
