### ISSUE TITLE
messed up theme

### ISSUE THREAD

**Issue by tavotevasas** [claudehohl/Stikked#369]
hey guys. so i've just installed it on my testing hosting, the main page looked all good, but after pressing submit, the outcome looks like something is bugged with the theme, tried changing the theme, still the same view... it looks like: http://i.imgur.com/MdktHhZ.png  how do I fix it?

**Comment by TurkDesk** [comment]
same problem when i install by git, however if u get from release and upload application folder again, it fixes must be some of latest commits maybe..

**Comment by mrc0mmand** [comment]
I have the same issue after upgrading to the latest master. After a quick investigation the issue is indeed in the last commit (e0680194f19466ee035c0db0af0106f748bc1719), because version without this commit works as expected (`git checkout ea465c2b3276a5de280e5ff68ba821494f0ba872`).

**Comment by Zwixx** [comment]
Hm, I can't find a issue. Do you use a custom config.php and not include the new 

`$config['favorite_languages'] = array('text', 'html5', 'css', 'javascript', 'php', 'python', 'ruby', 
	'lua', 'bash', 'erlang', 'go', 'c', 'cpp', 'diff', 'latex', 'sql', 'xml');`

**Comment by mrc0mmand** [comment]
My config.php is the unmodified original from the master. Nevertheless, after delving deeper into this issue I finally found the culprit, which was the config parser of CI. PR #370 should fix that.

**Comment by sl1pkn07** [comment]
same here

**Comment by claudehohl** [comment]
mrc0mmand's fix solves the issue. but unfortunately, in the new codeigniter version you are forced to set the base_url. see http://www.codeigniter.com/user_guide/installation/upgrade_303.html
