### ISSUE TITLE
Unable to load the requested class: Db_session

### ISSUE THREAD

**Issue by oberdeha** [claudehohl/Stikked#371]
Hello. I've installed Stikked and it works fine, but now I want to make an LDAP auth. 
Turned on it in stikked.php 
$config['require_auth'] = true;
Then make several changes in auth_ldap.php according to my domain server and i get this mistake "Unable to load the requested class: Db_session"

Log_file say's me next
tailf /tmp/ci.loglog-2016-07-26.php
INFO - 2016-07-26 13:27:41 --> Language file loaded: language/russian/stikked_lang.php
INFO - 2016-07-26 13:27:41 --> Database Driver Class Initialized
DEBUG - 2016-07-26 13:27:41 --> Carabiner: Library initialized.
INFO - 2016-07-26 13:27:41 --> Controller Class Initialized
INFO - 2016-07-26 13:27:41 --> Model Class Initialized
INFO - 2016-07-26 13:27:41 --> Model Class Initialized
DEBUG - 2016-07-26 13:27:41 --> Config file loaded: /var/www/html/Stikked/htdocs/application/config/geshi_languages.php
DEBUG - 2016-07-26 13:27:41 --> cURL Class Initialized
DEBUG - 2016-07-26 13:27:41 --> Auth_Ldap initialization commencing...
ERROR - 2016-07-26 13:27:41 --> Unable to load the requested class: Db_session

Stikked/htdocs/application/libraries/Auth_ldap.php
class Auth_Ldap {
    function __construct() {
        $this->ci =& get_instance();

        log_message('debug', 'Auth_Ldap initialization commencing...');

        // Load the session library
        $this->ci->load->library('db_session');

        // Load the configuration
        $this->ci->load->config('auth_ldap');

....
but I can't find where class 'db_session' is defined

Any suggestions.

Thank you for your replys

**Comment by claudehohl** [comment]
db_session is no more.

https://www.codeigniter.com/user_guide/installation/upgrade_300.html#step-6-update-your-session-library-usage

> The Session Library has been completely re-written in CodeIgniter 3 and now comes with a bunch of new features, but that also means that there are changes that you should make ...
