### ISSUE TITLE
option to use KeyCAPTCHA

### ISSUE THREAD

**Issue by TurkDesk** [claudehohl/Stikked#375]
Would be good to have this captcha option by https://www.keycaptcha.com/ as the others too easy too pass..

**Comment by claudehohl** [comment]
Nice!
Let's see if I have some time in this milestone for this.

**Comment by claudehohl** [comment]
http://f.scratchbook.ch/keyfucktcha.png

"Your subscription will expire on 2016-09-06", Watermarks, Ads...

Sorry, this will not happen.

**Comment by TurkDesk** [comment]
you could try the free option ? i really don't know if its just me but i do get hit by spams with the captchas of stikked at this moment so some other options may be good honestly..
Maybe simple security question setting can be done ? where we make a question and answer in config..
