### ISSUE TITLE
Field 'paste' doesn't have a default value

### ISSUE THREAD

**Issue by haliphax** [claudehohl/Stikked#378]
Tried to create a new paste this morning, and I received this error:

```
Field 'paste' doesn't have a default value

Filename: models/Pastes.php
Line Number: 140
```

**Comment by claudehohl** [comment]
Well, how did you do it? Where? At paste.scratchbook.ch? And what did you enter?

**Comment by haliphax** [comment]
I was creating a new paste with a simple URL, username, and password in it. I gave my name, left the default type as plain text, and used my personal Stikked installation. There were no special characters (aside from : and /) anywhere in the paste.

**Comment by haliphax** [comment]
Well, a fresh pull got rid of the error (though I had to doctor the `Cssmin.php` library to avoid a PHP warning about methods with the same name as their class not being constructors in future versions of PHP). However, encrypted pastes don't work now. I'll do a separate issue for that, I suppose.

**Comment by claudehohl** [comment]
Nice! Oh, maybe you can provide your changes to Cssmin.php here so that I can incorporate your changes into the repo? Would be great!

**Comment by haliphax** [comment]
I just changed the "cssmin" function to "__construct". I'll send a PR.
