### ISSUE TITLE
Captcha not working PHP7

### ISSUE THREAD

**Issue by hetisthijs** [claudehohl/Stikked#380]
Captcha image contains errors.

Any fix available?

**Comment by claudehohl** [comment]
do you have some error messages?

**Comment by claudehohl** [comment]
Since you are not responding, I assume you have fixed the error.

**Comment by hetisthijs** [comment]
I have not. I just couldn't find any errors beside in my browser, with the saying: couldn't load because image contains errors. Haven't you been able to reproduce it in PHP 7?

**Comment by claudehohl** [comment]
No, it works all fine here and I have PHP7 on debian testing. That's why I asked you for any useful hints or errors in any logfiles... Otherwise, it is difficult to find the error.

**Comment by menzbua** [comment]
I have the same issue. In my Setup the Captcha did not appear.

Fallowing Versions running on my Server:
PHP 7.0.18-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.18-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

Server version: Apache/2.4.18 (Ubuntu)
Server built:   2017-06-26T11:58:04

In the Accesslog of the Webserver i see 404 für the captcha
172.18.0.2 - - [08/Jul/2017:08:16:38 +0000] "GET /view/captcha?1499501797 HTTP/1.0" 404 466 "https://serv-ssl.menzns.de/stikked/" "Mozilla/5.0 (iPad; CPU OS 10_3_2 like Mac OS X) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.0 Mobile/14F89 Safari/602.1"

In the errorlog is nothing to see.

If you need any further Debugs please let me know.

Thanks

**Comment by menzbua** [comment]
Found it. You have to add the fallowing to your vhosts config:


        <Directory /var/www/html/>
             Options Indexes FollowSymLinks MultiViews
             AllowOverride All 
             Order allow,deny
             allow from all
        </Directory>
