### ISSUE TITLE
Encrypted paste without main textfield/reCAPTCHA

### ISSUE THREAD

**Issue by Eiki1** [claudehohl/Stikked#381]
If i create an encrypted paste, niether the reCAPTCHER nor the main textfield are mandatory. It's possible to submit without both of these.

**Comment by claudehohl** [comment]
That's intended, kind of.

* Encrypted pastes are private, so why bother asking for the captcha?
* Can't check the "contents" of an encrypted "" (empty string) textfield. Content is encrypted in the browser.

**Comment by Eiki1** [comment]
The captcha-check is important to prevent spam-bots from cluttering the database. Would it be possible to create a config-option so that the captcha is necessary? If you can't check wheather an encrypted text-box is empty, that's ok.

**Comment by claudehohl** [comment]
No, not another config option, we already have 8 (!!) different spam-prevention methods in the config (https://github.com/claudehohl/Stikked/blob/master/htdocs/application/config/stikked.php.dist#L194-L206) - the config gets cluttered...

I worked on the spamadmin, cleaning up the db should be much easier now.
