### ISSUE TITLE
404 with Nginx

### ISSUE THREAD

**Issue by seflue** [claudehohl/Stikked#382]
With Nginx I get a 404 page (generated from stikked) and I can't figure out where the problem is. Here is my Nginx config snipped:

<code>
    location /stikked {
        alias /var/www/stikked/htdocs;
        index index.php;
        expires 0;

```
    try_files $uri $uri/ /stikked/index.php;

    location ~ \.php$ {
        return 444;
    }

    if ($request_uri !~* ^/(static|favicon\.ico|robots\.txt))
    {
        rewrite ^/stikked/(.*)$ /stikked/index.php?/$1 last;
        break;
    }

    location = /stikked/index.php {
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_split_path_info ^/stikked(.+\.php)(.*$);
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
```

</code>
I tried it without the if-rewrite-block before - same result.

**Comment by plaguewolf** [comment]
i get the same, but with apache, and php7

**Comment by E-t-z** [comment]
Having the very same problem.

**Comment by plaguewolf** [comment]
I had thought it was a derp with mod_rewrite(? the url rewrite thingy, cant remember off hand) and php7, butt apparently its not php version specific...?

**Comment by claudehohl** [comment]
Can't reproduce. Have you tried it with the most recent master? Reopen if it still persists.
