### ISSUE TITLE
PHP7 Issue with Code Igniter

### ISSUE THREAD

**Issue by maxbbender** [claudehohl/Stikked#383]
Hey, might be missing something here but trying to install on a Ubuntu 16.04 box w/ php 7.0.8 and there is an issue with CodeIgniter error reporting. 

Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception

Issue is further described : http://stackoverflow.com/questions/36982769/codeigniter-ci-exceptionsshow-exception-error-after-updating-to-php-7

They said they fixed here : https://github.com/bcit-ci/CodeIgniter/issues/4137

And if you have updated to at least CI v3.0 + it should have been fixed which I saw you did in your most recent version update. 

Any ideas? lmk if you need some doc or other information.

**Comment by claudehohl** [comment]
> And if you have updated to at least CI v3.0 + it should have been fixed which I saw you did in your most recent version update.

Yes. Release is today :)

**Comment by maxbbender** [comment]
updated to 0.11 w/ CI 3.1 and it is working. Thanks! Love the geocities theme btw haha, got a good chuckle.

**Comment by claudehohl** [comment]
hellyeah! :) great you like it. I love it too :>
