### ISSUE TITLE
PHP error on Stikked 0.10 with SQLite

### ISSUE THREAD

**Issue by fanningert** [claudehohl/Stikked#384]
Hi, I installed 0.10.0 and get following error.
I only edit in the file `application/config/stikked.php` is to uncomment the line `$config['db_driver'] = 'sqlite';`.

Webserver: [Caddy](caddyserver.com)
PHP: 7.0.11 via PHP-FPM

I run stikked in a subdirectory of my domain.

```
Fatal error: Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of Error given, called in /srv/http/xxx/www.example.com/pastbin/system/core/Common.php on line 662 and defined in /srv/http/xxx/www.example.com/pastbin/system/core/Exceptions.php:190 Stack trace: #0 /srv/http/xxx/www.example.com/pastbin/system/core/Common.php(662): CI_Exceptions->show_exception(Object(Error)) #1 [internal function]: _exception_handler(Object(Error)) #2 {main} thrown in /srv/http/xxx/www.example.com/pastbin/system/core/Exceptions.php on line 190
```

Looks like the same error in the issue #383

**Comment by claudehohl** [comment]
0.10.0 is one year old; today I will release 0.11.0 which will be based on the master branch.

Download the newest version here: https://github.com/claudehohl/Stikked/archive/master.zip and tell me if the error still persists.

**Comment by fanningert** [comment]
Now I get this error.
```
An uncaught Exception was encountered

Type: Error

Message: Class 'SQLite3' not found

Filename: /srv/http/vienna.fanninger.at/www/pastbin/system/database/drivers/sqlite3/sqlite3_driver.php

Line Number: 89

Backtrace:

File: /srv/http/vienna.fanninger.at/www/pastbin/application/controllers/Main.php
Line: 41
Function: __construct

File: /srv/http/vienna.fanninger.at/www/pastbin/index.php
Line: 315
Function: require_once
```

SQLite driver for PHP is installed. Here the text from the `phpinfo()`.
```
pdo_sqlite
PDO Driver for SQLite 3.x	enabled
SQLite Library	3.14.2
```

**Comment by fanningert** [comment]
Ok, I found the problem. Skitted don't us the pdo_sqlite driver from php. Now I activated the sqlite3 driver and the error is away.

**Comment by claudehohl** [comment]
Wonderful, glad that you could fix it! \o/
