### ISSUE TITLE
Comments are turned into hyperlinks

### ISSUE THREAD

**Issue by GottemHams** [claudehohl/Stikked#385]
Some people use comments like `//this is a comment` which the syntax highlighter turns into `<a href="//this">`. Seems to me it should only apply if it's like `xxx://this`.

It occurs for any language by the way, even plain text.

**Comment by claudehohl** [comment]
URL-Hyperlinking is done via JavaScript.

https://paste.scratchbook.ch/view/60283b98
Raw: https://paste.scratchbook.ch/view/raw/60283b98

Its kind of annoying, but the original code isn't touched.

Here is the issue for the syntax highlighter: https://github.com/claudehohl/Stikked/issues/262

Maybe something to investigate for, in the javascript library.

**Comment by GottemHams** [comment]
Thanks to the commit referenced there I found what .js file and what line(s) I needed to edit. So thanks. =]
