### ISSUE TITLE
Error 1064 after upgrade

### ISSUE THREAD

**Issue by martincmelik** [claudehohl/Stikked#386]
Hi,

I just upgraded from 0.8.5 to 0.11. Even when I saved/modified stikked.conf as described in release notes, then I must modify config.php as well (```encryption_key``` not mentioned in instructions). Stikked was still throwing me SQL error. I tried files as ```sess_driver``` as well as memcached, but none of them works.

Here is the error:
```
A Database Error Occurred

Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SET `last_activity` = 1478238672, `user_data` = 'a:2:{s:9:\"user_data\";s:0:\"\"' at line 1

UPDATE SET `last_activity` = 1478238672, `user_data` = 'a:2:{s:9:\"user_data\";s:0:\"\";s:6:\"expire\";i:0;}' WHERE `session_id` = '04093ee8e6d5da7adfd04e99b932ee8e'

Filename: libraries/Session.php

Line Number: 289
```

And if I may one more thing, is there a chance how to disable "Download" functionality?

Thank you

**Comment by claudehohl** [comment]
is this error still happening? reopen if so.
