### ISSUE TITLE
Bootstrap: encrypting not working, stikkedizr: hamburger menue not working

### ISSUE THREAD

**Issue by Artemiis** [claudehohl/Stikked#388]
all said in title, i have tested latest git version and 0.11
These are the two best themes i.m.o.

**Comment by sflcnetwork** [comment]
I can confirm that encrypting is not working on bootstrap, just goes back to the main page, nothing in error logs

**Comment by claudehohl** [comment]
encryption in bootstrap works (for me), will test stikkedizr together with https://github.com/claudehohl/Stikked/issues/414
