### ISSUE TITLE
Enhancement: API set ID

### ISSUE THREAD

**Issue by jlpoolen** [claudehohl/Stikked#389]
I'm experiencing the value of having the ability to shoot items to Stikket from the command line.  During development, such as installing an operating system, seeking help from communities is critical, so it is helpful to be able post files and output to a web site that can then be referenced later by URLs.

I'm now going to embark on some shell scripts that automatically post various files and output from the command line and it would be really helpful if I could control the ID assigned.  Anonymity and garbling of IDs is not essential to me, I'd rather be able to name my pastes with something like:
2016_11_16_18_16_boot-grub-grub.cfg
2016_11_16_18_16_genkernal_session_fail
2016_11_16_18_16_yadda_yadda

I think it would be pretty easy to transport an ID parameter down to the insert statement and have a check/return if the ID is taken or should be versioned.  I suspect you do not have time for this enhancement, nonetheless if I pursue this, I'd like your thoughts and problems you foresee.

**Comment by claudehohl** [comment]
Actually, when you paste from the commandline using the API, stikked should return a paste's ID, as described under API:

> Return values
> On success, the API returns the paste URL: https://paste.scratchbook.ch/view/[pasteid]
