### ISSUE TITLE
Log.php - path

### ISSUE THREAD

**Issue by jlpoolen** [claudehohl/Stikked#390]
Log.php has at line 176:
`$filepath = $this->_log_path.'log-'.date('Y-m-d').'.'.$this->_file_ext;
`
There needs to be a path delimited after " $this->_log_path" and before "'log-'.date" for on Linux system, the absence of a delimited, e.g. "/", causes the program to hang.  I could not get any response and finally tracked down the problem to this missing path delimited.  I added "/"
`$filepath = $this->_log_path.'/log-'.date('Y-m-d').'.'.$this->_file_ext;
`
and then things started to work.

**Comment by claudehohl** [comment]
This is in system/core/Log.php, right? Then you may have found a bug in CodeIgniter, consider reporting the issue there: https://github.com/bcit-ci/CodeIgniter/issues
I won't touch anything inside /system.

**Comment by claudehohl** [comment]
https://github.com/claudehohl/Stikked/commit/72a692e6103a34258297bd8bebce842bd74584b8
