### ISSUE TITLE
PHP error for codemirror_modes

### ISSUE THREAD

**Issue by madspooky** [claudehohl/Stikked#392]
I upgraded from 0.9.0 to 0.11.0 and now I'm getting this at the bottom of each page:

A PHP Error was encountered

Severity: Notice

Message: Undefined variable: codemirror_modes

Filename: view/view_footer.php

Line Number: 6

Backtrace:

File: /var/www/html/themes/stikkedizr/views/view/view_footer.php
Line: 6
Function: _error_handler

File: /var/www/html/application/core/MY_Loader.php
Line: 173
Function: include

File: /var/www/html/application/core/MY_Loader.php
Line: 44
Function: _ci_load

File: /var/www/html/themes/stikkedizr/views/view/view.php
Line: 114
Function: view

File: /var/www/html/application/core/MY_Loader.php
Line: 173
Function: include

File: /var/www/html/application/core/MY_Loader.php
Line: 44
Function: _ci_load

File: /var/www/html/application/controllers/Main.php
Line: 663
Function: view

File: /var/www/html/index.php
Line: 315
Function: require_once

Any assistance would be appreciated.

**Comment by E-t-z** [comment]
Having same issue afte rupgrading from 0.10.0 to 0.11.0

Running stikked on Apache 2.4 and PHP 5.6

**Comment by E-t-z** [comment]
Fixed by: https://github.com/claudehohl/Stikked/issues/414
