### ISSUE TITLE
Cannot view anything but index.php, everything else "not found"

### ISSUE THREAD

**Issue by rvzm** [claudehohl/Stikked#395]
I'm attempting to get Stikked working, but i've run into an issue: recent doesnt show up, pastes dont show up, trending doesnt show up.

I have followed the install instructions, but for some reason i still get errors. and the pastes are being created.

**Comment by Technoturnovers** [comment]
can confirm, on my end pretty much everything is 404ing and the captcha doesnt show up

**Comment by Technoturnovers** [comment]
Found fix
you can fix this by adding index.php/ to your baseurl
ie, http://paste.com/index.php/

**Comment by brytorres** [comment]
Can confirm the fix by @Technoturnovers works!
