### ISSUE TITLE
New Bug Found

### ISSUE THREAD

**Issue by atsuyim** [claudehohl/Stikked#398]
How do i solve this issue??

A PHP Error was encountered

Severity: Warning

Message: mysqli::real_connect(): (HY000/1045): Access denied for user 'pastebin'@'localhost' (using password: YES)

Filename: mysqli/mysqli_driver.php

Line Number: 202

Backtrace:

File: C:\xampp\htdocs\pastebin\application\controllers\Main.php
Line: 41
Function: __construct

File: C:\xampp\htdocs\pastebin\index.php
Line: 315
Function: require_once

`A Database Error Occurred

Unable to connect to your database server using the provided settings.

Filename: C:/xampp/htdocs/pastebin/system/database/DB_driver.php

Line Number: 436`

**Comment by atsuyim** [comment]
yes i indeed checked my password etc but it seems that the problem lies somewhere in Main.php or DB_driver.php

**Comment by olenoerby** [comment]
You need to check the login permissions for the user on the MYSQL database. Does that user have access to the database 'pastebin'?

**Comment by claudehohl** [comment]
error on the user side, closing now.
