### ISSUE TITLE
Cron 404

### ISSUE THREAD

**Issue by y2kbadbug** [claudehohl/Stikked#399]
I just migrated the site to a server with PHP 7.  When running the link to the cron it returns a 404.

Verified the rewrite rules are in the vhost.  Cron key is correct.  Looking for more options to debug or how to fix.

Thanks

**Comment by JonathanNet** [comment]
I have the same problem with the 404 on cron, hope some one can help to get it working

**Comment by claudehohl** [comment]
I just tested stikked in the newly created PHP7-docker image and there, the /cron url works, but only if you also have the cron_key in config/stikked.php set. Otherwise, it will throw a 404.

Can you retest/validate your settings, and if it still persists, reopen this issue?
