### ISSUE TITLE
Feature: Maybe Moderator Accounts?

### ISSUE THREAD

**Issue by falceso** [claudehohl/Stikked#406]
I would like to suggest that we can have more than one moderator accounts? With that, you can include logs for security and permissions.

Thanks
falceso
_Pineappled Development_

**Comment by claudehohl** [comment]
I don't quite get it... There are no moderators (no users at all, and so no roles) - just passwords. We can think about it as soon as https://github.com/claudehohl/Stikked/issues/277 is implemented.
