### ISSUE TITLE
GeSHi error

### ISSUE THREAD

**Issue by xuxiaodong** [claudehohl/Stikked#407]
Using latest master branch of Stikked.

When posting YAML paste, I receive the following error:

```
A PHP Error was encountered

Severity: Notice

Message: Undefined offset: 0

Filename: geshi/geshi.php

Line Number: 3519

Backtrace:

File: /var/www/stikked/htdocs/application/libraries/geshi/geshi.php
Line: 3519
Function: _error_handler

File: /var/www/stikked/htdocs/application/libraries/geshi/geshi.php
Line: 2907
Function: parse_non_string_part

File: /var/www/stikked/htdocs/application/libraries/Process.php
Line: 45
Function: parse_code

File: /var/www/stikked/htdocs/application/models/Pastes.php
Line: 490
Function: syntax

File: /var/www/stikked/htdocs/application/controllers/Main.php
Line: 656
Function: getPaste

File: /var/www/stikked/htdocs/index.php
Line: 315
Function: require_once 
```

**Comment by Artemiis** [comment]
Can reproduce! Fix?

**Comment by claudehohl** [comment]
Geshi isn't maintained anymore :( http://qbnz.com/highlighter/

Fix? Switching to another syntax highlighter. Not a trivial task...

**Comment by ColdSphinX** [comment]
Latest News
GeSHi 1.0.9.0 Released
2017/05/13
In parallel to the previous release, I'm happy to provide you this release of GeSHi which is the first one targeting PHP7. I has NO new languages as those were all bundled with the previous release already.

This release includes only bugfixes for proper support of PHP 7. Although it likely runs on PHP 5 there will be no support to PHP versions prior to PHP 7. Some more details can be found in the changelog.
[http://qbnz.com/highlighter/news.php?id=135](url)

**Comment by claudehohl** [comment]
Wow, this is news!!

I didn't expect that to happen. Great!
Will take care of updating it.
