### ISSUE TITLE
Many errors after install

### ISSUE THREAD

**Issue by Banochkin** [claudehohl/Stikked#408]
Hi. I install Stikked on my vps with centos and vestacp. After instal i get this errors on main page:

> Warning: file_exists(): open_basedir restriction in effect. File(/tmp/ci.log) is not within the allowed path(s): (/home/admin/web/mysite.com/public_html:/home/admin/tmp) in /home/admin/web/mysite.com/public_html/system/core/Log.php on line 122
> 
> Warning: mkdir(): open_basedir restriction in effect. File(/tmp/ci.log) is not within the allowed path(s): (/home/admin/web/mysite.com/public_html:/home/admin/tmp) in /home/admin/web/mysite.com/public_html/system/core/Log.php on line 122
> 
> Warning: is_dir(): open_basedir restriction in effect. File(/tmp/ci.log) is not within the allowed path(s): (/home/admin/web/mysite.com/public_html:/home/admin/tmp) in /home/admin/web/mysite.com/public_html/system/core/Log.php on line 124
> 
> A PHP Error was encountered
> Severity: Warning
> Message: file_exists(): open_basedir restriction in effect. File(/tmp/ci.log) is not within the allowed path(s): (/home/admin/web/mysite.com/public_html:/home/admin/tmp)
> Filename: core/Log.php
> Line Number: 122
> Backtrace:
> File: /home/admin/web/mysite.com/public_html/index.php
> Line: 315
> Function: require_once
> 
> A PHP Error was encountered
> Severity: Warning
> Message: mkdir(): open_basedir restriction in effect. File(/tmp/ci.log) is not within the allowed path(s): (/home/admin/web/mysite.com/public_html:/home/admin/tmp)
> Filename: core/Log.php
> Line Number: 122
> Backtrace:
> File: /home/admin/web/mysite.com/public_html/index.php
> Line: 315
> Function: require_once
> 
> A PHP Error was encountered
> Severity: Warning
> Message: is_dir(): open_basedir restriction in effect. File(/tmp/ci.log) is not within the allowed path(s): (/home/admin/web/mysite.com/public_html:/home/admin/tmp)
> Filename: core/Log.php
> Line Number: 124
> Backtrace:
> File: /home/admin/web/mysite.com/public_html/index.php
> Line: 315
> Function: require_once

And this, when i try to post paste:

> Warning: file_exists(): open_basedir restriction in effect. File(/tmp/ci.log) is not within the allowed path(s): (/home/admin/web/mysite.com/public_html:/home/admin/tmp) in /home/admin/web/mysite.com/public_html/system/core/Log.php on line 122
> 
> Warning: mkdir(): open_basedir restriction in effect. File(/tmp/ci.log) is not within the allowed path(s): (/home/admin/web/mysite.com/public_html:/home/admin/tmp) in /home/admin/web/mysite.com/public_html/system/core/Log.php on line 122
> 
> Warning: is_dir(): open_basedir restriction in effect. File(/tmp/ci.log) is not within the allowed path(s): (/home/admin/web/mysite.com/public_html:/home/admin/tmp) in /home/admin/web/mysite.com/public_html/system/core/Log.php on line 124
> 
> A PHP Error was encountered
> Severity: Warning
> Message: file_exists(): open_basedir restriction in effect. File(/tmp/ci.log) is not within the allowed path(s): (/home/admin/web/mysite.com/public_html:/home/admin/tmp)
> Filename: core/Log.php
> Line Number: 122
> Backtrace:
> File: /home/admin/web/mysite.com/public_html/index.php
> Line: 315
> Function: require_once
> 
> A PHP Error was encountered
> Severity: Warning
> Message: mkdir(): open_basedir restriction in effect. File(/tmp/ci.log) is not within the allowed path(s): (/home/admin/web/mysite.com/public_html:/home/admin/tmp)
> Filename: core/Log.php
> Line Number: 122
> Backtrace:
> File: /home/admin/web/mysite.com/public_html/index.php
> Line: 315
> Function: require_once
> 
> A PHP Error was encountered
> Severity: Warning
> Message: is_dir(): open_basedir restriction in effect. File(/tmp/ci.log) is not within the allowed path(s): (/home/admin/web/mysite.com/public_html:/home/admin/tmp)
> Filename: core/Log.php
> Line Number: 124
> Backtrace:
> File: /home/admin/web/mysite.com/public_html/index.php
> Line: 315
> Function: require_once
> 
> A PHP Error was encountered
> Severity: Warning
> Message: curl_setopt_array(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set
> Filename: libraries/Curl.php
> Line Number: 199
> Backtrace:
> File: /home/admin/web/mysite.com/public_html/application/libraries/Curl.php
> Line: 199
> Function: curl_setopt_array
> File: /home/admin/web/mysite.com/public_html/application/libraries/Curl.php
> Line: 241
> Function: options
> File: /home/admin/web/mysite.com/public_html/application/libraries/Curl.php
> Line: 48
> Function: execute
> File: /home/admin/web/mysite.com/public_html/application/controllers/Main.php
> Line: 777
> Function: simple_get
> File: /home/admin/web/mysite.com/public_html/application/controllers/Main.php
> Line: 733
> Function: _valid_recaptcha
> File: /home/admin/web/mysite.com/public_html/application/controllers/Main.php
> Line: 463
> Function: run
> File: /home/admin/web/mysite.com/public_html/index.php
> Line: 315
> Function: require_once
> 
> A PHP Error was encountered
> Severity: Warning
> Message: Cannot modify header information - headers already sent by (output started at /home/admin/web/mysite.com/public_html/system/core/Exceptions.php:272)
> Filename: helpers/url_helper.php
> Line Number: 564
> Backtrace:
> File: /home/admin/web/mysite.com/public_html/application/controllers/Main.php
> Line: 492
> Function: redirect
> File: /home/admin/web/mysite.com/public_html/index.php
> Line: 315
> Function: require_once

Please help.

**Comment by claudehohl** [comment]
/tmp/ci.log is not in the allowed paths. Well, that's a PHP security setting. You can leave the entry blank, here: https://github.com/claudehohl/Stikked/blob/master/htdocs/application/config/config.php#L196-L204

All other errors are consequential errors.

**Comment by Banochkin** [comment]
Thanks!
