### ISSUE TITLE
How can i add new page?

### ISSUE THREAD

**Issue by Banochkin** [claudehohl/Stikked#409]
I create new file test.php in themes/mytheme/views/, opens mysite.com/test and get 404 error.

How can i add new page?

**Comment by claudehohl** [comment]
Well, Stikked is not a CMS ;)

Its not that trivial. You'd have to add a route in https://github.com/claudehohl/Stikked/blob/master/htdocs/application/config/routes.php#L47-L66, add a controller function in https://github.com/claudehohl/Stikked/blob/master/htdocs/application/controllers/Main.php and then a view file in https://github.com/claudehohl/Stikked/tree/master/htdocs/themes/default/views

But there is lots of software dedicated exactly for managing content, pages and menus. I would recommend using that, and stikked only as a pastebin.

**Comment by Banochkin** [comment]
Big thanks!

Stikked is better, than CMS. :) I need add just one page.
