### ISSUE TITLE
Custom title and meta-tags for pages

### ISSUE THREAD

**Issue by Banochkin** [claudehohl/Stikked#410]
Can i edit <title> and some meta-tags (<meta name="description"> and other) in <head> for each page (about, api, trends, ...)?

**Comment by claudehohl** [comment]
Title: https://github.com/claudehohl/Stikked/blob/master/htdocs/themes/default/views/defaults/header.php#L4-L15
(and meta tags in the same file).

**Comment by Banochkin** [comment]
I still do not understand. :( Can you give me, please, an example of code for <title> on /about and /api pages?

**Comment by Banochkin** [comment]
Or, maby i can add code, like
```
if (page = about) {
some code
} else if (page = api) {
some code
}
```
It's will be cool! :)
