### ISSUE TITLE
losted files - encrypted backup

### ISSUE THREAD

**Issue by arhu** [claudehohl/Stikked#415]
Hi, I was using stikked for long time, but my server go down and I lost some files but I was doing daily mysql backup. So I have got database with some encrypted pastes. How can I decrypt them? 

And is this chance, to install stikked again with old pasties?

**Comment by claudehohl** [comment]
The encrypted pastes are encrypted in the database (hence the name). You'll need the full URL of the paste to access and decrypt them (decryption key is part of the URL and not stored in the database).

**Comment by arhu** [comment]
so how i can decrypt them without access to files? Some pasties are not encrypted, but few are...

**Comment by arhu** [comment]
it is error when I install new files "Error Number: 1054
Unknown column 'private' in 'where clause'
SELECT id FROM pastes WHERE private = 0
Filename: models/Pastes.php
Line Number: 705"
