### ISSUE TITLE
Spamadmin IPv6 handling

### ISSUE THREAD

**Issue by ColdSphinX** [claudehohl/Stikked#422]
I noticed some errors if an ip address did not contain any dots due to beeing an ipv6 address, so I suggest something like this:

      //fill data
     $data = $this->pastes->getSpamLists('spamadmin/' . $ip_address, $seg = 3, $ip_address);
     $data['ip_address'] = $ip_address;
     $ip = explode('.', $ip_address);
     if (count($ip) > 1) {
       $ip_firstpart = $ip[0] . '.' . $ip[1] . '.';
       $data['ip_range'] = $ip_firstpart . '*.*';
     } else {
       // it's probably an ipv6 address
       $ip = explode(':',$ip_address);
       $ip_firstpart = $ip[0].':'.$ip[1].':'.$ip[2].':'.$ip[3].':'.$ip[4].':'.$ip[5].':'.$ip[6];
       $data['ip_range'] = $ip_firstpart.':*';
     }

Anyone a better idea or more places that need to be fixed?

**Comment by claudehohl** [comment]
Thanks!
