### ISSUE TITLE
404 with Apache

### ISSUE THREAD

**Issue by TheRealBards** [claudehohl/Stikked#423]
Hi,

I've just installed stikked on my server, and can get to the front page, write pastes to the database just fine, but when I try to access the paste or click on any of the links to the other pages, it doesn't work. I get a 404.

The access log shows the below:

    <ip_addr> - - [02/Jun/2017:16:33:56 +0100] "GET /lists HTTP/1.1" 404 497
    <ip_addr> - - [02/Jun/2017:16:33:57 +0100] "GET / HTTP/1.1" 200 4648
    <ip_addr> - - [02/Jun/2017:16:33:58 +0100] "GET /trends HTTP/1.1" 404 498
    <ip_addr> - - [02/Jun/2017:16:33:59 +0100] "GET / HTTP/1.1" 200 4648

I have a feeling that it might be a really simple fix, so sorry for wasting time if it is.

My PHP version is 7.0.18
My MySQL version is 5.7.18
My Apache version is 2.4.18
My OS is Ubuntu 16.04 server
I have the rewrite mode enabled

Any pointers would be a massive help!

Thanks in advance.

**Comment by The-Compiler** [comment]
Did you copy the `.htaccess` file correctly?

**Comment by TheRealBards** [comment]
It was exactly that, I had it in the incorrect folder. Knew it would be easy. Thanks for your help.
