### ISSUE TITLE
Delete posts

### ISSUE THREAD

**Issue by rojz** [claudehohl/Stikked#428]
Hello,

I have been trying to setup a stikked server where I got everything to work except that I would be able to delete posts easly without to be needed to go into the DB and delete it there, I found out that the spamadmin should be able to delete posts without any extra configuration, but I can't get it to work. What are the steps that are needed to get it to work?

- I have 2 stikked systems right now for testing (1 with FastCGI and 1 with PHP_mod).
both got the config/stikked.php file congifured for spamadmin
- I have uncommented the AuthType, AuthName, AuthUserFile and Require user in /htdocs/.htaccess
- I have created a .htpasswd file with the same user and pw as the stikked.php file.

Have I missed something or have I done something wrong? I'm not that experienced with codes like these.

I have been trying to follow issue #155 without any luck since I have the same problem.

**Comment by The-Compiler** [comment]
What does "can't get it to work" mean? What do you do, and what happens?

**Comment by rojz** [comment]
I can't login to the myserver/index.php/spamadmin and when I close the pop-up window, i get 2 errors:^

```
A PHP Error was encountered

Severity: Notice

Message: Undefined index: HTTP_AUTHORIZATION

Filename: controllers/Spamadmin.php

Line Number: 26

Backtrace:

File: /var/www/html/htdocs/application/controllers/Spamadmin.php
Line: 26
Function: _error_handler

File: /var/www/html/htdocs/index.php
Line: 315
Function: require_once
```

AND

```
A PHP Error was encountered

Severity: Notice

Message: Undefined offset: 1

Filename: controllers/Spamadmin.php

Line Number: 26

Backtrace:

File: /var/www/html/htdocs/application/controllers/Spamadmin.php
Line: 26
Function: _error_handler

File: /var/www/html/htdocs/index.php
Line: 315
Function: require_once
```

**Comment by rojz** [comment]
Anyone that know how to fix this? I'm kinda stuck.

**Comment by rojz** [comment]
Anyone that have any clue about this? Can't get it to work.

**Comment by claudehohl** [comment]
This should be fixed. My hoster switched to FastCGI as well and I encountered the same problem. Support-article: https://www.metanet.ch/support/502

Anyways, it should be fixed with those lines:
https://github.com/claudehohl/Stikked/blob/master/htdocs/application/controllers/Spamadmin.php#L25-L26
https://github.com/claudehohl/Stikked/blob/master/htdocs/.htaccess#L6-L7

So make sure you're using the most recent version.
