### ISSUE TITLE
CI update needed for "improved" PHP 7.1 session variable

### ISSUE THREAD

**Issue by fasterit** [claudehohl/Stikked#429]
Basically this hits stikked too:
https://github.com/bcit-ci/CodeIgniter/issues/4830

In php 7.1 are new session configuration values:
session.sid_length
session.sid_bits_per_character
http://php.net/manual/en/session.configuration.php#ini.session.sid-length
and thus default values regex: /^[0-9a-f]{40}$/ are not working anymore.

This breaks Stikked e.g. on Fedora 26 which has (mod_)php 7.1.6.
E.g. the Captcha won't work anymore with the default php.ini values.

**Comment by claudehohl** [comment]
relevant changelogs:

* https://www.codeigniter.com/user_guide/installation/upgrade_312.html
* https://www.codeigniter.com/user_guide/installation/upgrade_313.html

**Comment by claudehohl** [comment]
ci updated.
