### ISSUE TITLE
HTTPS support problem

### ISSUE THREAD

**Issue by ekianjo** [claudehohl/Stikked#431]
I have several web apps running on my server and none of them have problem using https::// as configured, however for some reason stikked throws some warnings that "parts of this page are not secure (for example images)" in Firefox. 

Is there something that needs to be done to make stikked support https fully on the server side? (i use nginx)

**Comment by seitzbg** [comment]
I've not seen this and I too use HTTPS via nginx for my Stikked instance.

**Comment by claudehohl** [comment]
Can't reproduce as well. All resources on https://paste.scratchbook.ch/ load via https.

Make sure your base-url contains https as well.
