### ISSUE TITLE
"Create encrypted" doesn't works with php7+

### ISSUE THREAD

**Issue by Razva** [claudehohl/Stikked#433]
Nothing happens when clicking on "Create encrypted" when using php7+. After clicking the page simply reloads, without any result. You can test on https://p.bsd-unix.net/

**Comment by seitzbg** [comment]
I have the same problem, please advise :)

**Comment by claudehohl** [comment]
I'll have to investigate.

**Comment by srvrguy** [comment]
What theme are you using? I've seen similar behavior on PHP 5.6 using Bootstrap. It works on "default", however.

**Comment by Razva** [comment]
> What theme are you using? I've seen similar behavior on PHP 5.6 using Bootstrap. It works on "default", however.

Same goes here, Bootstrap theme. So I guess it's a theme issue, not a system issue?

**Comment by claudehohl** [comment]
it works now, ci has been updated to be compatible with php7 (hopefully, I haven't tested it for myself :) )
