### ISSUE TITLE
Markdown syntax feature request

### ISSUE THREAD

**Issue by CompuRoot** [claudehohl/Stikked#434]
This question already raised an year ago in [issue#361](https://github.com/claudehohl/Stikked/issues/361) and it was closed.

 Could you please take a look at https://github.com/erusev/parsedown. Pretty decent and well supported product IMHO. It used in well known projects. 
Fork of original [PasteBin](https://github.com/jordansamuel/PASTE) using it together with Geshi as: 

    // Apply syntax highlight
    $p_content = htmlspecialchars_decode($p_content);
    if ( $p_code == "markdown" ) {
        include( $parsedown_path );
        $Parsedown = new Parsedown();
        $p_content = $Parsedown->text( $p_content );
    } else {
        $geshi     = new GeSHi($p_content, $p_code, $path);
        $geshi->enable_classes();
        $geshi->set_header_type(GESHI_HEADER_DIV);
        $geshi->set_line_style('color: #aaaaaa; width:auto;');
        $geshi->set_code_style('color: #757584;');
        if (count($highlight)) {
            $geshi->enable_line_numbers(GESHI_NORMAL_LINE_NUMBERS);
            $geshi->highlight_lines_extra($highlight);
            $geshi->set_highlight_lines_extra_style('color:#399bff;background:rgba(38,92,255,0.14);');
        } else {
            $geshi->enable_line_numbers(GESHI_FANCY_LINE_NUMBERS, 2);
        }
        $p_content = $geshi->parse_code();
        $style     = $geshi->get_stylesheet();
        $ges_style = '<style>' . $style . '</style>';
    }
so I hope it wouldn't be hard to use both parsers in the same time.
 

By the way, Geshi is still in business (last update May, 2017) and [support PHP7](http://qbnz.com/highlighter/news.php?id=135)

**Comment by claudehohl** [comment]
Umm, no, we'd need a MarkDown *Highlighter*, not a parser. And I updated Geshi to the most recent version.
