### ISSUE TITLE
"Paste it" on Android crashes on Android 7

### ISSUE THREAD

**Issue by wioxjk** [claudehohl/Stikked#441]
When trying to make a paste

**Comment by The-Compiler** [comment]
If you mean [this app](https://play.google.com/store/apps/details?id=org.teamblueridge.pasteitapp), this should probably go to [their issue tracker](https://jira.teamblueridge.org/projects/PASTE/issues
)

**Comment by wioxjk** [comment]
That app yes,
Yeah, I tried that issue tracker after I vrote this.

The description of Stikked here on github seems to give an hint that "Paste it" is very related to stikked, or infact made by the author

**Comment by SimonSickle** [comment]
https://github.com/teamblueridge/PasteIt please put your report here and a logcat if possible

**Comment by wioxjk** [comment]
@SimonSickle 
Thanks, I will!

**Comment by kylelaker** [comment]
Relevant: teamblueridge/PasteIt#7

I will submit a PR to remove the link from the README until the app can be fixed.
