### ISSUE TITLE
Setup automated build on Docker Hub

### ISSUE THREAD

**Issue by Joeasaurus** [claudehohl/Stikked#442]
I am interested in running Stikked on my Docker infrastructure and I notice you've been thinking the same thing!

It would be really handy if you could set up and automated build on Docker Hub against this repo, so there's a public image of your Dockerfile for people to pull. I would like to use my own docker-compose.yml without needing to build your image, like so:

```yaml
stikked:
  image: claudehohl/stikked:latest
```

and have it automatically pull from the hub :)

I hope that makes sense?

**Comment by The-Compiler** [comment]
cc @Th3R3p0 who did the Docker image.

**Comment by Joeasaurus** [comment]
Temporarily, I'm hosting it internally and building with the Dockerfile changed slightly to this:

```Dockerfile
RUN apt update && apt install -y git
RUN git clone https://github.com/claudehohl/Stikked.git
RUN cp -r Stikked/htdocs/* /var/www/html/
RUN cp -r /var/www/html/application/config/stikked.php.dist /var/www/html/application/config/stikked.php
RUN cp -r Stikked/replace-envvars.sh /bin/
RUN cp -r Stikked/docker-php-entrypoint /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-php-entrypoint
```

**Comment by Th3R3p0** [comment]
@claudehohl - do you want to setup an account on docker hub? I figure that would look better since you manage this repo. The we can add this as the source and build it on the hub. https://docs.docker.com/docker-hub/builds/ 

I tested it on docker hub and i have it working at `docker pull th3r3p0/stikked`

**Comment by Joeasaurus** [comment]
@claudehohl Indeed the reason I raised the issue here is only the repository owner can add an "automatic build" on the hub, as you have to link your GitHub account for it to read the repository list. 

I'm with @Th3R3p0 it will probably look nicer having @claudehohl 's name all over it as well :) And thanks for the temp hosted version mate even if it is behind!

**Comment by christronyxyocum** [comment]
Any update on this? Could @Th3R3p0 update his Docker image so it's not behind? What port is this set to listen on/have exposed by default?

**Comment by claudehohl** [comment]
...and here we go: https://hub.docker.com/r/claudehohl/stikked/
