### ISSUE TITLE
Use of demo site for paste apps

### ISSUE THREAD

**Issue by SimonSickle** [claudehohl/Stikked#444]
Hello! I have worked closely on the android app and have designed the iOS paste app. I would like to revitalize both applications and utilize the http://paste.scratchbook.ch/ domain and its API. Do I have permission to do so @claudehohl 

iOS - https://github.com/teamblueridge/PasteNow
Android - https://github.com/teamblueridge/PasteIt

**Comment by claudehohl** [comment]
Of course! That's great.

**Comment by SimonSickle** [comment]
May I know the API key for your site, as well! Thanks in advance!

If you want to keep this private, my email is github@simonsickle.com

**Comment by claudehohl** [comment]
sent to you via mail.
