### ISSUE TITLE
config.php

### ISSUE THREAD

**Issue by shadowlmd** [claudehohl/Stikked#449]
I want to redefine some $config stuff, i.e. $config['uri_protocol'] and $config['rewrite_short_tags'] in stikked.php but it doesn't work, so I have to modify config.php itself, and it gets overwritten with every update. This is kinda annoying. Is there a way to move this stuff to stikked.php?

**Comment by Th3R3p0** [comment]
Are you updating via git? This would fix your issue

```
git stash
git pull origin master
git stash pop
```

**Comment by shadowlmd** [comment]
Yeah, I know there are ways to work it around. I chose to fork this repo and merge new commits manually. But this is not how it supposed to work in general.

**Comment by claudehohl** [comment]
yea config.php is for codeigniter-settings, not meant to be modified; and stikked.php is for user-facing settings.

So, at the moment, config.php gets overwritten.

**Comment by timwhite** [comment]
@claudehohl Some of the things in config.php do need to be modified. e.g. proxy_ips. What can we do to stop it getting overwritten? Can we have it include another file that is similar to stikked.php that doesn't get overwritten?

**Comment by The-Compiler** [comment]
Sounds to me like Stikked should expose `proxy_ips` (and maybe more?) in `stikked.php` like it already does with e.g. `base_url`.
