### ISSUE TITLE
Regular captcha is displayed instead of reCaptcha in reply form

### ISSUE THREAD

**Issue by shadowlmd** [claudehohl/Stikked#454]
I've configured reCaptcha and it's displayed properly on main page, but in reply form I still have to enter regular annoying captcha. I know that once I pass the captcha, it's saved in session and not displayed again. This happens when someone gets a link to a paste and wants to reply.

**Comment by claudehohl** [comment]
Ok, I'll investigate.

**Comment by wioxjk** [comment]
confirming this

**Comment by maop** [comment]
Hello came to report the same =)
It displays regular captcha when visiting /view/XXXXXX  in the reply form.
And when you fail the regular captcha it reloads but with the reCaptcha now... 

Thank you for your time.

**Comment by srvrguy** [comment]
I just tried to reproduce this with the latest code and can't get it to happen. I also tried switching themes and I keep getting the reCAPTCHA form, not the built-in. I'm testing on localhost, so that may be part of why I cannot reproduce this.

**Comment by kriegeralex** [comment]
Hi,

same problem here.
But only if reply to a private paste.

Regards

**Comment by Th3R3p0** [comment]
On private pages to @kriegeralex point I am seeing `$use_recaptcha` being `false` instead of `true`

https://github.com/claudehohl/Stikked/blob/master/htdocs/themes/default/views/defaults/paste_form.php#L115

**Comment by Th3R3p0** [comment]
This should be good to merge
