### ISSUE TITLE
LDAP Auth (AD windows)

### ISSUE THREAD

**Issue by oberdeha** [claudehohl/Stikked#455]
Hi every one.
Sorry for stupid question maybe, but I have error when I turned on "$config['require_auth'] = true;"
and make this changes to auth_ldap.php
$config['hosts'] = array('ip_add_AD_controller');
$config['ports'] = array(389);
$config['basedn'] = 'dc=*******,dc=******';
$config['login_attribute'] = 'uid';

And got this error

A PHP Error was encountered

Severity: Warning

Message: ldap_bind(): Unable to bind to server: Can't contact LDAP server

Filename: libraries/Auth_ldap.php

Line Number: 181

Backtrace:

File: /var/www/html/Stikked-master/htdocs/application/libraries/Auth_ldap.php
Line: 181
Function: ldap_bind

File: /var/www/html/Stikked-master/htdocs/application/libraries/Auth_ldap.php
Line: 92
Function: _authenticate

File: /var/www/html/Stikked-master/htdocs/application/controllers/Auth.php
Line: 74
Function: login

File: /var/www/html/Stikked-master/htdocs/index.php
Line: 315
Function: require_once

**Comment by The-Compiler** [comment]
"Unable to bind to server: Can't contact LDAP server"

Nothing more to add to that, really. Make sure it's actually reachable.

**Comment by oberdeha** [comment]
after changing $config['ports'] = array(389); to $config['ports'] = array(3268); the error was changed 

A PHP Error was encountered
Severity: Warning
Message: ldap_search(): Search: Operations error
Filename: libraries/Auth_ldap.php
Line Number: 192
Backtrace:
File: /var/www/html/Stikked-master/htdocs/application/libraries/Auth_ldap.php
Line: 192
Function: ldap_search
File: /var/www/html/Stikked-master/htdocs/application/libraries/Auth_ldap.php
Line: 92
Function: _authenticate
File: /var/www/html/Stikked-master/htdocs/application/controllers/Auth.php
Line: 74
Function: login
File: /var/www/html/Stikked-master/htdocs/index.php
Line: 315
Function: require_once
A PHP Error was encountered
Severity: Warning
Message: ldap_get_entries() expects parameter 2 to be resource, boolean given
Filename: libraries/Auth_ldap.php
Line Number: 193
Backtrace:
File: /var/www/html/Stikked-master/htdocs/application/libraries/Auth_ldap.php
Line: 193
Function: ldap_get_entries
File: /var/www/html/Stikked-master/htdocs/application/libraries/Auth_ldap.php
Line: 92
Function: _authenticate
File: /var/www/html/Stikked-master/htdocs/application/controllers/Auth.php
Line: 74
Function: login
File: /var/www/html/Stikked-master/htdocs/index.php
Line: 315
Function: require_once
A PHP Error was encountered
Severity: Warning
Message: file_put_contents(application/logs/audit.log): failed to open stream: Permission denied
Filename: libraries/Auth_ldap.php
Line Number: 139
Backtrace:
File: /var/www/html/Stikked-master/htdocs/application/libraries/Auth_ldap.php
Line: 139
Function: file_put_contents
File: /var/www/html/Stikked-master/htdocs/application/libraries/Auth_ldap.php
Line: 197
Function: _audit
File: /var/www/html/Stikked-master/htdocs/application/libraries/Auth_ldap.php
Line: 92
Function: _authenticate
File: /var/www/html/Stikked-master/htdocs/application/controllers/Auth.php
Line: 74
Function: login
File: /var/www/html/Stikked-master/htdocs/index.php
Line: 315
Function: require_once

**Comment by The-Compiler** [comment]
cc @lightswitch05 who implemented LDAP auth

**Comment by lightswitch05** [comment]
Sorry, I do not use Stikked or PHP anymore, so I'm not going to be much help.

Stikked isn't actually handling any of the LDAP logic, it is all managed [Auth_Ldap](https://github.com/gwojtak/Auth_Ldap). Look at their [example config](https://github.com/gwojtak/Auth_Ldap/blob/master/config/auth_ldap.php).

Your error is here:

> ldap_get_entries() expects parameter 2 to be resource, boolean given

I looks like there is a log feature in Auth_Ldap (`auditlog`) - maybe look at the logs to discover clues. If all else fails, fire up your debugger and step through the code. I'm sure pull requests are welcome if you find something wrong.

**Comment by oberdeha** [comment]
I've modified /htdocs/application/libraries/Auth_ldap.php pasted there code below and this is worked for me. Then I've added name = $_SESSION in paste form and selects to show only this users pastes in recent pastes. Thanks for all your replies and your product at all.

Have a nice day/evening

issue could be closed

`        $bind = ldap_bind($this->ldapconn, $binddn, $password);
        if(! $bind) {
            $this->_audit("Failed login attempt: ".$username." from ".$_SERVER['REMOTE_ADDR']);
            return FALSE;
        }
        $cn = $entries[0]['cn'][0];
        $dn = stripslashes($entries[0]['dn']);
        $id = $entries[0][$this->login_attribute][0];

        $get_role_arg = $id;

        return array('cn' => $cn, 'dn' => $dn, 'id' => $id,
            'role' => $this->_get_role($get_role_arg));*/

        $ldaphost = "xxx.xxx.xxx.xxx";
        $ldapport = "3268";
        $memberof = "CN=Domain Users,CN=Users,DC=xxxxxxxxx,DC=xxxxxxx";
        $base = "DC=playtika,DC=local";
        $filter = "uid=";
        $domain = "@xxxxxxx.xxx";
        $login = $username.$domain;

        $ldap = ldap_connect($ldaphost, $ldapport) or die("Cant connect to LDAP Server");
        ldap_set_option($ldap, LDAP_OPT_REFERRALS, 0);
        ldap_set_option($ldap, LDAP_OPT_PROTOCOL_VERSION, 3);
            if ($ldap)
                {
                $bind = ldap_bind($ldap, $login, $password);

                if($bind){
                    if(!isset($_SESSION)){
                        session_start();
                    }
                    $_SESSION['logged_user'] = $username;
                //    echo $_SESSION['logged_user'];
                //    exit ;
                    return true;
                } else {
                    $this->_audit("Failed login attempt: ".$username." from ".$_SERVER['REMOTE_ADDR']);
                }
            }

    }`
