### ISSUE TITLE
Improve the documentation on database configuration

### ISSUE THREAD

**Issue by tYYGH** [claudehohl/Stikked#461]
Hi! I’m trying to configure Stikked for PostgreSQL through PDO. It seems that I have to:
* set `$config['db_driver']='pdo'` in `config/stikked.php`
* set `$db['default']['subdriver']='pgsql'` and 
* set `$db['default']['dsn']='pgsql:host=…;port=…;dbname=…;user=…;password=…'` in `config/database.php`

None of this is documented. Assuming the above is right, I had to browse the code to arrive at this conclusion. The documentation does not even mention that the default driver is mysqli…

A better documentation about database configuration would be great!

**Comment by dlangille** [comment]
I am struggling with the same issue.  Copying the above, I get this error:

```
could not find driver

Filename: controllers/Main.php

Line Number: 41

**Comment by tYYGH** [comment]
Sure, but unless I am wrong, PDO is now the way to go for database access in PHP. And it is far from trivial to set up in Stikked…

**Comment by dlangille** [comment]
I'll leave it to you to figure out what best for you and whether or not PDO is preferred.  I do not wish to discuss that point.

In the meantime, I'll use what appears to be a legitimate approach given the code I've been reading.

**Comment by tYYGH** [comment]
@dlangille To each their own, of course. But your comments are off-topic.
This issue is mine, and I clearly state that I wish to use PDO, which is obviously possible, looking at the code. But how?…
