### ISSUE TITLE
Can't seem to install properly

### ISSUE THREAD

**Issue by WikiCopter** [claudehohl/Stikked#462]
Followed all the instructions and installed at paste.jeremywang.org

Installation doesn't seem to work, every time I access the installation it displays a blank page and tries to download a 4kb file.

Tested multiple times, without success.

**Comment by The-Compiler** [comment]
Does your PHP installation work? Can you show e.g. a [phpinfo file](https://mediatemple.net/community/products/dv/204643880/how-can-i-create-a-phpinfo.php-page) correctly?

**Comment by WikiCopter** [comment]
That's funny - the same thing happens when I created a phpinfo file and tried to access it. I'm guessing the problem is on my end, and I will contact my webhost about it. Thanks!

**Comment by GaneshKandu** [comment]
Getting same problem
index.php is getting download when i am hitting url 
i think its not related to host its related to .htaccess comment this line in .htaccess
```
AddHandler php5-fastcgi .php .php5
```

**Comment by WikiCopter** [comment]
@GaneshKandu My issue was resolved when I contacted my webhost. They said they updated the PHP version.

**Comment by GaneshKandu** [comment]
Oh! 
What is your Current PHP version
Thanks @WikiCopter
