### ISSUE TITLE
404 Not Found for Everything but the homepage.

### ISSUE THREAD

**Issue by Icalestro** [claudehohl/Stikked#463]
I wanted to test this thing out and it worked, but when I created a paste, 404 not found. I tried clicking on trending and all that other jazz. Turns out everything but the base page gives the error 404. 

i am running this on 000webhost if that makes any difference.

**Comment by Th3R3p0** [comment]
Did you copy your .htaccess file correctly?

**Comment by Th3R3p0** [comment]
Also try uncommenting line https://github.com/claudehohl/Stikked/blob/master/htdocs/.htaccess#L2 in the .htaccess file out per https://www.000webhost.com/website-faq/do-you-support-htaccess-what-should-i-know-about-it-16

**Comment by Icalestro** [comment]
@Th3R3p0 Is there supposed to be an .htaccess in the github source? I'm on a Mac, so I don't see it?

**Comment by Th3R3p0** [comment]
If you run `ls -alh` from the terminal you will see the .htaccess file in the htdocs directory. Dot files are not displayed in finder or by default in the terminal. the `-a` flag will show you these files.

**Comment by dlangille** [comment]
The problem may be base_url.

**Comment by 6-ril** [comment]
Hi,
I have the same issue.
I modify .httpd to change RewriteBase / to RewriteBase /paste/ (my subfolder) but it still not help.

For me, there's something wrong with rewriting but I can't find what. 
In apache2.err, I just have error like :
[Fri Apr 06 14:25:41 2018] [error] [client xx.xx.xx.xx] File does not exist: /var/www/paste/view, referer: https://le-repaire.ovh/paste/

Any idea please ?

**Comment by claudehohl** [comment]
> I get the same issue using Nginx.
> 
> Reading https://github.com/claudehohl/Stikked/blob/master/doc/webserver_sampleconfigs/nginx-site.conf and using the first example got it working for me.

So I consider the issue resolved. RTFM actually helps :)
