### ISSUE TITLE
Create, send paste from command line (.bashrc)

### ISSUE THREAD

**Issue by freeroute** [claudehohl/Stikked#466]
Is it possible to create, send paste(s) from command line (add an alias to .bashrc) like here: https://transfer.sh/#samples
e.g.: $ stikked -d private=1 -d name=my_name hello.txt 
or 
$ stikked -d private=1 -d name=my_name hello.txt  https://freeroute.sytes.net/api/create

**Comment by The-Compiler** [comment]
Yes, see e.g. https://paste.scratchbook.ch/api

**Comment by freeroute** [comment]
Yes, I read that. How can I do?
If I create an alias in .bashrc:
#stikked alias
alias stikked='curl -d private=1 -d name=freeroute  https://freeroute.sytes.net/api/create'

than try to run, got an error: 
root@Xenon-XR3:~# stikked 
Error: Missing paste text

**Comment by The-Compiler** [comment]
I'm not sure what you expect that to do. Just like the error message says, you'll need to have a text to paste.

**Comment by freeroute** [comment]
I would like to create a paste from a file using command line, using an alias. .bashrc contains:
alias stikked='curl -d private=1 -d name=freeroute https://freeroute.sytes.net/api/create'

Like here: https://transfer.sh/#samples

> "Add an alias to .bashrc 
> # Now you can use transfer command
> $ transfer hello.txt "

**Comment by The-Compiler** [comment]
So take the example on how to paste a file:

```bash
curl -d private=1 -d name=Herbert --data-urlencode text@/etc/passwd https://paste.scratchbook.ch/api/create
```

And make a bash alias out of that, e.g.:

```bash
stikked() { curl -d name="$1" --data-urlencode text@"$1" https://paste.scratchbook.ch/api/create ;}
```

(untested). This really isn't the right place to get bash support :wink:
