### ISSUE TITLE
Error: You are not allowed to paste.

### ISSUE THREAD

**Issue by freeroute** [claudehohl/Stikked#467]
Today I got an error message after to try create a paste.
"You are not allowed to paste."

So I can't create a paste. Do you have any idea what happened?
What shall I check?

**Comment by The-Compiler** [comment]
When pasting where?

**Comment by freeroute** [comment]
This is my server: https://freeroute.sytes.net/
Until to this day, everything work well.

**Comment by The-Compiler** [comment]
Sounds like you blocked yourself via spamadmin. Check the `blocked_ips` table in your database.
