### ISSUE TITLE
Error: Module 'memcached' already loaded 

### ISSUE THREAD

**Issue by sigrony** [claudehohl/Stikked#468]
hey there,
after a clean installation I get this error.
I'm new to PHP, maybe it's something very obvious. What do I need to change to fix this issue? 
Thank you. 👍 

Severity: Core Warning
Message: Module 'memcached' already loaded
Filename: Unknown
Line Number: 0
Backtrace:

**Comment by The-Compiler** [comment]
Sounds like an issue with your PHP installation and not Stikked. Does your PHP installation work? Can you show e.g. a [phpinfo file](https://mediatemple.net/community/products/dv/204643880/how-can-i-create-a-phpinfo.php-page) correctly?

**Comment by sigrony** [comment]
If I remove the .htaccess I can display an phpinfo file with out a problem.

**Comment by shadowlmd** [comment]
That is definitely not related to Stikked. Message is from PHP and means that `extension=memcached.so` exists in more than one ini file.

**Comment by sigrony** [comment]
Okay but could it be, that this error could interrupt Strikked, because since then the post won't delete themselfs. Is the error the cause?

**Comment by shadowlmd** [comment]
This is not an error at all, just a warning. And it is not related to Stikked in any way. Check your server configuration.
