### ISSUE TITLE
Data is modified before saving to database

### ISSUE THREAD

**Issue by dlangille** [claudehohl/Stikked#469]
HTML tags are modified before saving to the database.

Data should be saved unmodified.

For example:

```
<?php
```

Is saved as:

```
&lt;?php
```

**Comment by claudehohl** [comment]
I know! This is the behaviour of Stikked long even before I took over as a maintainer. I decided to leave it like that, for the sake of compatibility...

**Comment by dlangille** [comment]
I will look at adding an option.  I have fixed it locally.

**Comment by fasterit** [comment]
This could have security implications, too. So consider auditing that before a too hasty release. Just sayin'.

**Comment by claudehohl** [comment]
I don't see any new code besides a config flag "true_paste". And no, I don't want another config flag, the config is already overloaded.
I'd solve it by using a converter/migration to run either the old or the new version, depending on if the converter has already run or not.

Don't worry, I release yearly, usually by the end of September.

**Comment by dlangille** [comment]
The code is run through htmlentities on the way out.

**Comment by dlangille** [comment]
Later this week, I'll release a FreeBSD port with the new configuration flag.

**Comment by dlangille** [comment]
Re: I don't see any new code besides a config flag "true_paste"

I will check the repo when I get to the office.  The code part is missing from the pull request.

**Comment by shadowlmd** [comment]
This patch still looks incomplete to me because if you change how data is stored, you need to change how data is displayed. I see only first part. Since you are not running it through htmlspecialchars(), there may be some weird issues with displaying pastes containing `&amp;`, `&lt`, etc.

**Comment by dlangille** [comment]
Are you saying the display side does not run it through htmlspecialchars?

Have you looked at that side of the code yet?

**Comment by shadowlmd** [comment]
I didn't check the code yet, but it seems obvious to me that htmlspecialchars() would not be called twice, one time when paste is stored and another time when it's displayed. So when you choose not to encode special chars at store time, you need to add htmlspecialchars() at places when pastes are getting displayed.

**Comment by shadowlmd** [comment]
I also don't like another thing about it. Since there can be old pastes done without true_paste option, turning this option on will make old pastes display incorrectly. A much better approach would be to introduce a new filed like `version` and set version to 1 for unmodified pastes. This way old and new pastes could be displayed properly.

**Comment by dlangille** [comment]
Do have a search, you might be surprised by what is not so obvious.

**Comment by shadowlmd** [comment]
Well, I did search and found exactly what I expected to find:
```
$data['paste'] = $this->process->syntax(htmlspecialchars_decode($row['raw']) , $row['lang']);
```
Which means that `&lt;` will be converted to `<` by this code, if you store a paste containing `&lt;`. Exactly what I have said earlier. Correct me if I am wrong.

**Comment by maop** [comment]
So my site is having a problem, it displays correctly the code:
$mail->IsSMTP();
$mail->SMTPDebug = 1;
$mail->SMTPAuth = true;
$mail->SMTPSecure = 'ssl';

But in the "reply to..." box it shows:

$mail-&gt;IsSMTP();
$mail-&gt;SMTPDebug = 1;
$mail-&gt;SMTPAuth = true;
$mail-&gt;SMTPSecure = 'ssl';

How could i fix this?
