### ISSUE TITLE
Composer compatibility ?

### ISSUE THREAD

**Issue by rroblik** [claudehohl/Stikked#473]
Hi !

First off all thanks for all the hard work done on it project !

I just want to know if there is any chance to see a *native* composer dependency ? 
As this is a php project I think it's not far away right now !

Regards

**Comment by Th3R3p0** [comment]
Hey @rroblik! 

What do you mean by _"native"_?

**Comment by rroblik** [comment]
Hi !

Sorry for the delay ...

I mean available through `composer ` :)
