### ISSUE TITLE
Im a beginner and I had this issues#  403 forbidden access to this resource on the server is denied

### ISSUE THREAD

**Issue by freeboy1367** [claudehohl/Stikked#474]
When I open this page: mydomain.com/stikked/  this error came....Please guide me with simple method...thank you..

403 forbidden access to this resource on the server is denied

**Comment by shadowlmd** [comment]
You obviously need to learn how to set up a webserver. There are plenty of manuals on the net. This is the first one I found in google, looks pretty simple: https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-on-ubuntu-16-04

**Comment by freeboy1367** [comment]
Thanks about that but consider My hosting is shared hosting so I have not SSH access...

**Comment by The-Compiler** [comment]
This still looks like an issue with your web hoster, and not Stikked. You might want to start with getting a basic [phpinfo file](https://mediatemple.net/community/products/dv/204643880/how-can-i-create-a-phpinfo.php-page) to run, and contact your hoster for assistance.
