### ISSUE TITLE
Entity Encoding of XML & HTML in Proposed Reply Editor

### ISSUE THREAD

**Issue by jlpoolen** [claudehohl/Stikked#476]
When I create a paste of content type XML and HTML, the view of the paste I created then has a proposed reply that contains the contents where special characters are encoded using entities.  If I use the default text in the editor in a reply, then the next generation will have certain markings encoded rather than as the characters.  Example: the "<" becomes an entity &lt;

See samples:
Sample XML 1    https://paste.scratchbook.ch/view/7df35388
Sample HTML 1   https://paste.scratchbook.ch/view/d6372510

**Comment by jonkloske** [comment]
I have the same problem, version 0.12.0. Just confirming it's affecting more than one person :D

**Comment by claudehohl** [comment]
It's already fixed in the master-branch (https://github.com/claudehohl/Stikked/commit/615119a496a5229cf59534c540f9ccafddb53520); I just didn't want to tag another release because of one change.

And I finally uploaded the fixed files to the demosite. Your samples are looking great :)
