### ISSUE TITLE
Exact steps for stikked's Setup 

### ISSUE THREAD

**Issue by freeboy1367** [claudehohl/Stikked#478]
Its been  a few days that I stucked with stikked..Except one time that It installed by my hosting provider but It has error of 404# in all links except homepage...

After that I removed Stikked to re-install it again....But It only shows a white blank screen.Now I asked from experts here Whats the Setup steps exactly? Its mean I copy and extract it then edit stikked.php with base-url and database ......Is anything more need for install of stikked? Please show me a simple manuall for setup of stikked As Im a beginner for desingning a blog......

**Comment by freeboy1367** [comment]
Can anybody install it for me?

**Comment by The-Compiler** [comment]
Did you see the installation docs in the readme?

**Comment by freeboy1367** [comment]
thanks..I hired a script expert and he installed for me...

**Comment by The-Compiler** [comment]
Glad to hear you got it working! Closing this then.
