### ISSUE TITLE
Confirmation for Stikked php run on LiteSpeed web Servers

### ISSUE THREAD

**Issue by freeboy1367** [claudehohl/Stikked#479]
I need a Confirmation for Stikked php run on LiteSpeed web Servers from Script developers of Stikked php...

Tnx

**Comment by The-Compiler** [comment]
Well, you won't. How would we know? Why not just try it out?

**Comment by freeboy1367** [comment]
Because Im begineer and I tried to install it  but nothing except a white page comes...


Only one time stikked installed in my capanel but except homepage all pages had error of 404...

My hosting provider asked me those question that I asked....Its more than 2 weeks that I stucked for Stikked setup...
