### ISSUE TITLE
Cron

### ISSUE THREAD

**Issue by medioaker** [claudehohl/Stikked#482]
Hi, I know I sound like a complete idiot, but I have no idea what to do with the cron section. Everything is setup besides it. Pastes are working and can be posted, but if I set an expiration, they stay forever anyway. How do I setup cron? I have no idea what I'm doing and googling it didn't help.

**Comment by mrc0mmand** [comment]
Hi,

First, you have to set up a `cron_key` in [<stikked_root>/application/config/stikked.php](https://github.com/claudehohl/Stikked/blob/master/htdocs/application/config/stikked.php.dist#L93-L100). Use something random as a key, e.g.:
```sh
$ cat /dev/urandom | head -n1 | md5sum
a7be6a8ae967a0183f2bd2cde2223f01  -
```

So the `cron_key` in stikked.php would look like this:
```php
$config['cron_key'] = 'a7be6a8ae967a0183f2bd2cde2223f01';
```

Finally, set a cron job to call the Stikked's cron endpoint regularly (either using user-specific crontab or a system crontab):
```sh
# crontab -u apache -e
```

For this you can use the exampe from the config file, so the final crontab will look like this:
```sh
# crontab -u apache -l
*/5 * * * * curl --silent http://yoursite.com/cron/a7be6a8ae967a0183f2bd2cde2223f01
```

Replace the `apache` user to the user which your web server is running under (and don't forget to replace the curl's URL to a correct address of your Stikked installation).

Hope this makes the cron setup clear.
