### ISSUE TITLE
Encrypt pastes 

### ISSUE THREAD

**Issue by oberdeha** [claudehohl/Stikked#485]
Sorry, this is not an issue, I want only to ask, because I haven't found this in documentation, how is encryption works. I create encrypted past,  then, what shell I do to open it?  I understand, that it's all made for some kind of security,  but how could I decrypt  it?
Thanks for your reply's

**Comment by The-Compiler** [comment]
With the encryption key which is part of the URL.

**Comment by oberdeha** [comment]
Thank you

**Comment by ronv** [comment]
Hey! I have same issue as @oberdeha on last comment. Is there any fix for that?
