### ISSUE TITLE
Encrypted pastes are not syntax highlighted

### ISSUE THREAD

**Issue by Peetz0r** [claudehohl/Stikked#491]
When I create an encrypted paste with a specific language, it does not syntax highlight. The exact same text does work fine with a normal paste.

Examples:
https://paste.sigio.nl/view/8692d036
https://paste.sigio.nl/view/af84fa7c#wc84UwNjzAlGElMMhcbxQmH48K3zHybO

I am guessing that this requires moving the syntax highlighting which is now done by Geshi in PHP in to some other library in JS.

**Comment by claudehohl** [comment]
Exactly. I wanted to keep additional JS away from encrypted pastes. Probably there is some sensitive information being shared in encrypted pastes, which shouldn't be altered.
