### ISSUE TITLE
Encrypted paste doesn't decrypt

### ISSUE THREAD

**Issue by ronv** [claudehohl/Stikked#494]
Hi,

Theme stikkedizr always shows encrypted message even if I have use link with hash

https://xxx.xxx.xxx.xxx/view/195716a8
https://xxx.xxx.xxx.xxx/view/195716a8#40T7DTlOe2gqoEWuMd3TNSoclIMRkWs7

Shows on encrypted paste :
U2FsdGVkX19G07a8nMAUj6upQpJYZQ+jkooZFoO93ME=

Any fix for this?

**Comment by The-Compiler** [comment]
Do you have JavaScript enabled?

**Comment by ronv** [comment]
@The-Compiler Yes, here is example:

https://camo.li/paste/view/9f01f301
https://camo.li/paste/view/9f01f301#IzozU0mnmR3p89ej8kunGVQUAviYFzGD

Both of them are encrypted.
Maybe you know where the problem may be?

**Comment by claudehohl** [comment]
Hmm, codemirror_exec.js couldn't be loaded. Might Codemirror interfere with the js encryption? I have to recreate that scenario. Stay tuned.

**Comment by ronv** [comment]
Hey! Any fix for this? 

Br, Ron

**Comment by claudehohl** [comment]
duplicate #499
