### ISSUE TITLE
Upgrade From 0.10 Era To Latest Problems

### ISSUE THREAD

**Issue by tundratim** [claudehohl/Stikked#496]
We've been running a version of Stikked from over 2 years ago and it's worked just fine.

We are using Apache to rewrite everything to https and encrypting everything with letsencrypt certs for the virtual host running Stikked.

When we attempt to upgrade to latest version from the repo, it tries to work, but never renders the GUI properly.   If we try to click on, say, the "Recent" button, we get an error complaining that the cert is not valid for the host in question.   For some reason Stikked is trying to use the host's IP rather than the virtual host name (for which the cert was generated).

Any ideas on this?

**Comment by The-Compiler** [comment]
Do you have `$config['base_url']` set correctly in your config?

**Comment by tundratim** [comment]
Yep, that was the issue, thanks.

Any idea why 0.10 didn't need this and now we do?

**Comment by The-Compiler** [comment]
No clue - I suppose CodeIgniter tries to auto-detect the value if not set, and maybe something changed about how that works.
