### ISSUE TITLE
comment of c++ will be seen as url

### ISSUE THREAD

**Issue by 1049451037** [claudehohl/Stikked#498]
```cpp
//cout << tmp;
```
the "//cout" will be a hyperlink in the Stikked page.

**Comment by The-Compiler** [comment]
It is technically a valid URL, but not a very useful one. Not sure if Stikked can do anything about it though, or if that's a GeSHi feature.

**Comment by claudehohl** [comment]
It's a JS feature. I let http://soapbox.github.io/linkifyjs/ replace all possible URLs with a clickable link.
https://github.com/claudehohl/Stikked/blob/master/htdocs/themes/default/js/linkify.min.js

Maybe I can tune the settings a bit.
