### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by stevesbrain** [claudehohl/Stikked#500]
Hey all,

Running 0.12.0, if I try and do a new paste, I get:

```

A PHP Error was encountered

Severity: Error

Message: Call to undefined method CI_Input::method()

Filename: libraries/Form_validation.php

Line Number: 171

Backtrace:
```

Commenting out the following lines resolves the issue, but I'm not sure if this is introducing any security risk, or simply avoiding applying rules to blank pastes? Please advise :)

https://github.com/claudehohl/Stikked/blob/c24e053f0e43c12c7f8805c0f9abf0a7134714a4/htdocs/system/libraries/Form_validation.php#L171-L174

**Comment by claudehohl** [comment]
Can't reproduce. I'm running 0.12.0, fresh install, and creating pastes works.
Also, the line you wanted to comment out is in the system folder, which means standard CodeIgniter stuff. That should definitely work and shouldn't be touched.

**Comment by stevesbrain** [comment]
Odd, but appreciate the input! I'll look into it from my end and see what I can determine :) Mine was an upgrade from an older version, so perhaps upgrading is part of the issue. Thanks!
