### ISSUE TITLE
Not being able to access index.php page. 

### ISSUE THREAD

**Issue by pxoss** [claudehohl/Stikked#501]
Hello, i put all the stikked files in my pastebin folder. I have already changed the database part of the config file to the below. I have changed a bit in the configuration files, such as the author name and expired message. I am running PHP 5.6 with php_gd. Apache shared hosting. Default Perms 644 for all files. 
`$config['db_hostname'] = '127.0.0.1;`

`$config['db_database'] = 'pxoss_pastebin';`

`$config['db_username'] = 'pxoss_stikked';`

`$config['db_password'] = 'NICE-TRY';`

**Comment by The-Compiler** [comment]
This sounds like your PHP installation is broken, you might try getting a [phpinfo page](https://mediatemple.net/community/products/dv/204643880/how-can-i-create-a-phpinfo.php-page) to run first.

**Comment by pxoss** [comment]
phpinfo page works, i also have a php upload script that 100% works on the same website

**Comment by pxoss** [comment]
big facepalm, i think it was the php instalation and how i overwritten the  .htaccess from the original one (had php info) to current one. i had a phpinfo test running on the main domain, not the sub domain. i tried to perform the test on the subdomain and had the same effect as the pastebin index.php page. anyways thanks

**Comment by The-Compiler** [comment]
Closing this then, as it's not a stikked issue.
