### ISSUE TITLE
installation doesn't say anything about mcrypt

### ISSUE THREAD

**Issue by odilitime** [claudehohl/Stikked#504]
our encryption broke and I think it was because we didn't have mcrypt installed. It'd be nice if the README would clarify (or if any other libraries are needed for optional functionality)

**Comment by claudehohl** [comment]
Well I dunno, it wasn't required for the docker image. Maybe mcrypt is installed by default in most distributions?

(see https://github.com/claudehohl/Stikked/blob/dev/docker/php/Dockerfile)
