### ISSUE TITLE
Internal Captcha broken in Docker

### ISSUE THREAD

**Issue by Nebukadneza** [claudehohl/Stikked#512]
In the current docker container, non-recaptcha generation is broken. The call to `/views/captcha?...` returns a php stacktrace rather than jpeg image data. The interesting part is:
`Call to undefined function ImageJPEG()`
As far as I understand, this is because the `GD` extension bundled with the baseimage is built without jpeg support. I was able to fix this by:
```
apt install libjpeg62-turbo-dev libfreetype6-dev
docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
docker-php-ext-install gd 
```
Which is … a fair bit ugly. But still, maybe we want this in our `Dockerfile` …?

Thanks for the great project! ^_^
Best,
-Dario

**Comment by claudehohl** [comment]
rewriting the whole docker setup fixes so many issues :)

check out the dev-branch, it works now.
