### ISSUE TITLE
Allow expiration burn pastes regardless of spam settings

### ISSUE THREAD

**Issue by dopaminereceptionist** [claudehohl/Stikked#513]
expiration=burn pastes should be safe most of the time, especially expiration=burn and private=1.

**Comment by claudehohl** [comment]
I've thought about it and well, actually no.
One could still spam the database, and I can't catch expiration=burn pastes with the cronjob; since they have no expiration (except someone visits them). I can't just delete all expiration=burn pastes, because that would also catch all unread burnpastes.
