### ISSUE TITLE
htacces

### ISSUE THREAD

**Issue by linhux** [claudehohl/Stikked#515]
Hi i have trobble with the htacces, so when i deaktivaet the htacces can i acces the index but when i enable the htaccess it will download the index.php

**Comment by linhus** [comment]
so there is also an issue with the views, when i create at pastebin he cannot find the link.
https://doamin.net/view/856d85f8 not found

**Comment by linhus** [comment]
i have disabled the htaccess, but the views are not found

**Comment by rob-lindman** [comment]
look at the htaccess in trunk, the one in the zip is wrong.

**Comment by claudehohl** [comment]
New release is coming soon and the .htaccess and zips will be updated. Stay tuned.
