### ISSUE TITLE
centos 7 and new user

### ISSUE THREAD

**Issue by ecsuae** [claudehohl/Stikked#516]
hi ,i am trying to configure stikked on centos 7 , captcha is not showing , if i try to create a post i simple get error
ip/view/7651105a was not found on this server.
i copied .htaccess content from the github.i am not sure if setting are correct or not.
RewriteEngine on
#RewriteBase /
RewriteCond $1 !^(index\.php|\.well-known|static|favicon\.ico|robots\.txt|sitemap.xml|google(.+)\.html)
RewriteRule ^(.*)$ index.php?/$1 [QSA,L]

# basic auth for PHP with fastcgi
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]

SetOutputFilter DEFLATE
FileETag MTime Size

<IfModule !mod_rewrite>
    ErrorDocument 404 /index.php
</IfModule>

<IfModule mod_expires>
    ExpiresActive On
    ExpiresByType text/javascript "access plus 1 year"
    ExpiresByType application/x-javascript "access plus 1 year"
    ExpiresByType application/javascript "access plus 1 year"
    ExpiresByType text/css "access plus 1 year"
    ExpiresByType image/jpeg "access plus 1 year"
    ExpiresByType image/jpg "access plus 1 year"
    ExpiresByType image/gif "access plus 1 year"
    ExpiresByType image/png "access plus 1 year"
    ExpiresByType image/x-icon "access plus 1 year"
    ExpiresByType application/font-woff "access plus 1 year"
    ExpiresByType application/vnd.ms-fontobject "access plus 1 year"
    ExpiresByType application/x-font-ttf "access plus 1 year"
    ExpiresByType font/opentype "access plus 1 year"
    ExpiresByType image/svg+xml "access plus 1 year"
</IfModule>

#AuthType Basic
#AuthName "Backend"
#AuthUserFile /path/to/.htpasswd #create one with htpasswd -c .htpasswd username
#Require user username

AddHandler php5-fastcgi .php .php5 .php

can anyone help?

**Comment by claudehohl** [comment]
Try the docker-setup (check out dev-branch). At least the captcha error should be gone; I'll investigate the basic auth issue tomorrow.
