### ISSUE TITLE
Malicious posts

### ISSUE THREAD

**Issue by matdejfirst** [claudehohl/Stikked#517]
Hey, hope all is going well, these users are using your service to spread malicious links leading to trojans and cryptocurrency miners, please do something about it. 

https://paste.scratchbook.ch/view/5eac7d4c
https://paste.scratchbook.ch/view/7a316d79
https://paste.scratchbook.ch/view/8634a10c
https://paste.scratchbook.ch/view/820faec8

Regards.

**Comment by claudehohl** [comment]
Thanks. Took care of it.

I also cleaned up this moronic football-spammers.
