### ISSUE TITLE
Syntax Highlighting causing timeout

### ISSUE THREAD

**Issue by stukkat** [claudehohl/Stikked#519]
The following code, when entered into stikked and any kind of syntax highlighting applied on my server will cause the server to throw an error and wont save. It will save in plain text just fine. I tried entering it on the demo site and it saves flawlessly with highlighting.

I'm running stikked on a windows server, apache 2.4.27, php 5.6.31.

`list TDM = [<4.1, 5.1, 6.1>, <1.1, 3.1, 9.1>, <3.1, 6.1, 2.1>, <8.1, 1.1, 3.1>, <2.2, 8.4, 5.5>, <7.5, 1.5, 2.8>, <5.0, 1.3, 8.4>, <3.7, 9.4, 6.4>, <3.7, 7.7, 6.9>, <3.9, 8.6, 5.6>, <1.2, 7.8, 6.4>, <6.9, 4.2, 2.1>, <4.1, -5.1, 6.1>, <1.1, 3.1, -9.1>, <-3.1, 6.1, -2.1>, <8.1, -1.1, -3.1>, <-1.7, 3.7, -6.9>, <-3.9, -8.6, -5.6>, <-2.2, 8.4, -5.5>, <-7.5, 1.5, -2.8>, <-5.0, -1.3, 8.8>, <3.7, -9.4, 6.4>, <-1.0, -3.3, 5.4>, <-3.1, -3.8, 7.2>, <-9.0, -2.3, -6.1>, <-14.7, -1.6, 9.3>];`

I tried removing some of the entries and it seems to be a parse error.

`Message: Undefined offset: 1
Filename: geshi/geshi.php
Line Number: 3502

File: x:\server\public_html\tools\pastebin\application\libraries\geshi\geshi.php
Line: 3502
Function: _error_handler
File: x:\server\public_html\tools\pastebin\application\libraries\geshi\geshi.php
Line: 3060
Function: parse_non_string_part
File: x:\server\public_html\tools\pastebin\application\libraries\Process.php
Line: 45
Function: parse_code
File: x:\server\public_html\tools\pastebin\application\models\Pastes.php
Line: 522
Function: syntax
File: x:\server\public_html\tools\pastebin\application\controllers\Main.php
Line: 697
Function: getPaste
File: x:\server\public_html\tools\pastebin\index.php
Line: 315
Function: require_once`

Any suggestions you could give me would be much appreciated.

**Comment by claudehohl** [comment]
Well, this is Geshi, which unfortunately doesn't get developed anymore :(
https://sourceforge.net/projects/geshi/files/

And indeed, your code with highlighting works fine on the demo instance (and also my local docker-instance). https://paste.scratchbook.ch/view/b8c9379f

Difficult to see what causes that problem with your setup.
