### ISSUE TITLE
Docker build error: ifstream::ifstream (13: Permission denied)

### ISSUE THREAD

**Issue by AnywherePear** [claudehohl/Stikked#523]
`sudo docker build -t stikked .
`
Sending build context to Docker daemon  47.97MB
Step 1/7 : FROM php:7.1-apache
 ---> ba77ddc3b7b7
Step 2/7 : EXPOSE 80
 ---> Using cache
 ---> 76bc857008e6
Step 3/7 : RUN apt-get -y update && 	apt-get -y install libpng-dev zlib1g-dev cron && 	echo apt-get -y install vim mysql-client && 	a2enmod rewrite && 	docker-php-ext-install mysqli gd && 	rm -rf /var/lib/apt/lists/*
 ---> Running in dab54631c866
**E: Opening configuration file /etc/apt/apt.conf.d/01autoremove - ifstream::ifstream (13: Permission denied)**
The command '/bin/sh -c apt-get -y update && 	apt-get -y install libpng-dev zlib1g-dev cron && 	echo apt-get -y install vim mysql-client && 	a2enmod rewrite && 	docker-php-ext-install mysqli gd && 	rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
master@stik:~/Stikked$ sudo docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                        PORTS               NAMES
dab54631c866        76bc857008e6        "/bin/sh -c 'apt-get…"   37 seconds ago      Exited (100) 34 seconds ago                       affectionate_liskov
d9a298610ecd        76bc857008e6        "/bin/sh -c 'apt-get…"   57 seconds ago      Exited (100) 56 seconds ago                       zen_bose

**Comment by claudehohl** [comment]
I rewrote the docker setup.

Check out the dev branch and try, it should be working now :)
