### ISSUE TITLE
Running on WAMP?

### ISSUE THREAD

**Issue by jimpriest** [claudehohl/Stikked#524]
Anyone got Stikked running on WAMP?

Trying to set this up on a clunker laptop for our team.  It runs, but I've had to comment out all of the .htaccess to get it to run.  And no CSS / JS loads.

**Comment by jimpriest** [comment]
May be related to #515?  Going to compare those files and see if they are different.

**Comment by claudehohl** [comment]
I have no experience with Stikked on WAMP, so closing due inactivity.
