### ISSUE TITLE
Can't login in spamadmin

### ISSUE THREAD

**Issue by vOidSenses** [claudehohl/Stikked#527]
I'm reading this issues for hours now and I simply cannot figure out what I'm doing wrong.

Let me say in advance I understand very little about server configurations. I looked and I'm running my server with CGI/FastCG, and I can't login to the spamadmin page, the prompt keeps showing up repeatedly. From the other closed issues it seems this is something in which a workaround has already been implemented but it still doesn't work here. ( yes, user and pass are setted )

I don't know how related this is to the login issue but I had to comment out the AddHandler in my htaccess file to make everything work or else it would keep downloading the pages instead of rendering them.

What exactly do I need to do to be able to login?

**Comment by claudehohl** [comment]
The current (rewritten) docker setup is a cgi-like setup. I just tested it and it works - maybe you can cross-check your configuration with the docker configs? https://github.com/claudehohl/Stikked/tree/dev/docker
