### ISSUE TITLE
Fix htdocs/.htaccess

### ISSUE THREAD

**Issue by vsafr** [claudehohl/Stikked#528]
Hi!

`RewriteCond $1 !^(index\.php|\.well-known|static|favicon\.ico|robots\.txt|sitemap.xml|google(.+)\.html)`

This shall include 'themes' otherwise it rewrites to index.php and makes useless php call.

`<IfModule mod_expires>` should be `<IfModule mod_expires.c>` with `.c`

**Comment by claudehohl** [comment]
appending .c to modules: yes, including themes in rewrite-rule: no. We have .php files inside themes that wouldn't get parsed: https://github.com/claudehohl/Stikked/tree/master/htdocs/themes/default/views

https://github.com/claudehohl/Stikked/commit/09435ff69a574fa783873dd26516788cf0a06f4f
