### ISSUE TITLE
Blank Page on embed iframe Code

### ISSUE THREAD

**Issue by Happyfeet01** [claudehohl/Stikked#530]
Hello,

i would integrate some Paste´s on my Wordpress Blog.
But i only get a white Page when i insert the Code into my Blogpost.

<iframe src="https://paste.dasnetzundich.de/view/embed/007e551b" style="border:none;width:100%"></iframe>

When i insert an other Website it works.

**Comment by Happyfeet01** [comment]
Any idea @claudehohl

**Comment by claudehohl** [comment]
Hard to tell in a vacuum. Do you have an actual page where the iframe is embedded so that I can take a look too?

**Comment by Happyfeet01** [comment]
Look here https://dasnetzundich.de/testpage-for-irames/

**Comment by The-Compiler** [comment]
@Happyfeet01 Neither iframe there works for me. It looks like your server (as well as Google) sends `X-Frame-Options: SAMEORIGIN` which disallows embedding the website in a frame (see [docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options))

**Comment by Happyfeet01** [comment]
Okay thanks

**Comment by Happyfeet01** [comment]
Found the settings,fixed.
