### ISSUE TITLE
Doesn't work with MySQL 8

### ISSUE THREAD

**Issue by pcolmer** [claudehohl/Stikked#531]
The provided `docker-compose.yml` references `mysql:latest`, which will use MySQL 8.0. Attempting to use Stikked with that results in database connection failure.

If MySQL 5.7 is explicitly requested in `docker-compose.yml`, this works.

**Comment by claudehohl** [comment]
Jup, thanks!

I rewrote the whole docker setup. It now uses mariadb 10.4.
