### ISSUE TITLE
Sub-directories under themes/.../images not allowed

### ISSUE THREAD

**Issue by pcolmer** [claudehohl/Stikked#532]
It doesn't seem to be explicitly stated in the documentation but it looks like `Theme_assets.php` indirectly prohibits the use of sub-directories under the `images` folder in a theme.

I raise this because it took me a while to figure out why a theme we use with an older version of Stikked wasn't loading images on the new version.

**Comment by claudehohl** [comment]
Yea, also for performance reasons...

Thanks for the hint. I mentioned in the docs: https://github.com/claudehohl/Stikked/commit/50fd78d85eeac13a4870fcc6668d2885ff0535ce
