### ISSUE TITLE
Disable Captcha

### ISSUE THREAD

**Issue by rob151515** [claudehohl/Stikked#533]
This could be a user error rather than a code issue but just wanted to make note of it in case it is a bug or in case it's helpful to anyone else trying to set this up.

I got this project running in Docker last night using docker-compose. What I had trouble with was the environment variable 'STIKKED_ENABLE_CAPTCHA'.

Setting this variable to false in my docker-compose file did not seem to make any difference. I was unable to disable the captcha.

In the end to disable the captcha I had to remove that variable from my compose file and instead set the appropriate config value in stikked.php.dist to false inside the container and restart.

Great project by the way.

**Comment by claudehohl** [comment]
I completely rewrote the docker-setup.

https://github.com/claudehohl/Stikked/commit/4462a471c516691ccc4dcb335d74063dae1ecd8f

Should be working now! :) (Currently only in the dev-branch)
