### ISSUE TITLE
IPv6 too long?

### ISSUE THREAD

**Issue by Gunni** [claudehohl/Stikked#543]
See

![hpP3Sd9](https://user-images.githubusercontent.com/358099/98004874-5922c080-1de8-11eb-8583-f547a4478a71.png)

**Comment by fasterit** [comment]
Thanks for the report @Gunni.
This was caused by the database not having been updated when the host got IPv6 added.
The field used to be a `varchar(16)` and now is a `varchar(45)` in stikked's code. But it did not upgrade the database schema.
This issue can be closed.
