### ISSUE TITLE
Howto set other theme or language ?

### ISSUE THREAD

**Issue by woeperbe** [claudehohl/Stikked#545]
Sorry but i can't find where to define what theme to use ?
Did i miss something ?

**Comment by The-Compiler** [comment]
In the config file - see the [example file](https://github.com/claudehohl/Stikked/blob/master/htdocs/application/config/stikked.php.dist) shipping with Stikked.

**Comment by woeperbe** [comment]
Woeps sorry
Thanks for the quick reply
