### ISSUE TITLE
How do I get an API key for a site?

### ISSUE THREAD

**Issue by AggamR** [claudehohl/Stikked#552]
CentOS paste uses Stikked and I was cannot find a way to get an API key.
When I visit [](https://paste.centos.org/api/random) I always get `Invalid API key` so I wanted to know how I get one. Thx.

**Comment by The-Compiler** [comment]
The API key is [set in the config](https://github.com/claudehohl/Stikked/blob/master/docker/stikked.php#L206), so you'd need to contact whoever is hosting that page (i.e. presumably CentOS server admins).
