### ISSUE TITLE
Syntax highlight cause PHP crash

### ISSUE THREAD

**Issue by martincmelik** [claudehohl/Stikked#85]
Hi,

please check this paste: http://paste.scratchbook.ch/view/8ea711b0
It will end with 500 Internal Server Error

Paste is same as this: http://paste.scratchbook.ch/view/8610b209
But in this case without syntax highlighting.

Thank you

**Comment by claudehohl** [comment]
Oh men. Geshi seems dead... Closing for now, bummer.
